(function(){'use strict';
var S={tab:'overview',auto:true,universe:[],ticks:{},kl:{},analysis:{},positions:[],history:[],equity:10000,realized:0,fees:0,risk:.5,deep:0,opt:[],marks:{},error:'',started:Date.now()},busy=false,cursor=0,optBusy=false,FEE=.0005,MAXM=3,MAXS=3,MAXO=4,DAILY=-.03;
var N=function(x){x=Number(x);return isFinite(x)?x:0},M=function(x){return '₹'+N(x).toLocaleString('en-IN',{maximumFractionDigits:2})},Pct=function(x){return (N(x)>=0?'+':'')+N(x).toFixed(2)+'%'},E=function(x){return String(x==null?'':x).replace(/[&<>]/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;'}[c])})};
function save(){try{localStorage.setItem('bd-v7',JSON.stringify({positions:S.positions,history:S.history.slice(-500),equity:S.equity,realized:S.realized,fees:S.fees,risk:S.risk}))}catch(e){}}
function load(){try{var x=JSON.parse(localStorage.getItem('bd-v7')||localStorage.getItem('bd-v6')||'{}');if(x.positions)S.positions=x.positions;if(x.history)S.history=x.history;if(N(x.equity)>0)S.equity=N(x.equity);S.realized=N(x.realized);S.fees=N(x.fees);S.risk=N(x.risk)||.5}catch(e){}}
function api(p){return fetch('/api/binance-market?path='+encodeURIComponent(p),{cache:'no-store'}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw Error('API response invalid ('+r.status+')')}if(!r.ok)throw Error((j&&j.error)||('Binance API '+r.status));return j})})}
function ema(a,p){if(!a.length)return 0;var k=2/(p+1),e=N(a[0]);for(var i=1;i<a.length;i++)e=N(a[i])*k+e*(1-k);return e}
function atr(a){if(a.length<15)return 0;var s=0;for(var i=a.length-14;i<a.length;i++){var h=N(a[i][2]),l=N(a[i][3]),pc=N(a[i-1][4]);s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/14}
function rsi(a,p){p=p||14;if(a.length<=p)return 50;var g=0,l=0,i;for(i=a.length-p;i<a.length;i++){var d=N(a[i])-N(a[i-1]);if(d>0)g+=d;else l-=d}if(l===0)return 100;var rs=(g/p)/(l/p);return 100-100/(1+rs)}
function spike(a){if(a.length<12)return 0;var s=0;for(var i=a.length-11;i<a.length-1;i++)s+=N(a[i][5]);return N(a[a.length-1][5])/Math.max(s/10,1e-9)}
function body(a){var x=a[a.length-1];return Math.abs(N(x[4])-N(x[1]))/Math.max(N(x[2])-N(x[3]),1e-9)}
function analyze(sym){var k=S.kl[sym],t=S.ticks[sym];if(!k||!t)return{signal:'WATCH',score:0,mScore:0,sScore:0,atr:0};var m1=k.m1||[],m5=k.m5||[],m15=k.m15||[];if(m1.length<25||m5.length<25||m15.length<25)return{signal:'WATCH',score:0,mScore:0,sScore:0,atr:0};
var c1=m1.map(function(x){return N(x[4])}),c5=m5.map(function(x){return N(x[4])}),c15=m15.map(function(x){return N(x[4])}),p5=c5[c5.length-2],l5=c5[c5.length-1],l15=c15[c15.length-1],e5=ema(c5,9),e21=ema(c5,21),e15=ema(c15,13),e1=ema(c1,9),R5=rsi(c5,14),R1=rsi(c1,14),v5=spike(m5),v1=spike(m1),b5=body(m5),b1=body(m1),a=atr(m5),r5=(l5-p5)/Math.max(p5,1e-9),r1=(c1[c1.length-1]-c1[c1.length-2])/Math.max(c1[c1.length-2],1e-9);
var mb=l5>e5&&e5>e21&&l15>e15&&r5>0&&R5>=52&&R5<=78&&t.c>0,vb=l5<e5&&e5<e21&&l15<e15&&r5<0&&R5<=48&&R5>=22&&t.c<0;
var sb=r1>0&&r5>0&&c1[c1.length-1]>e1&&R1>52&&R1<78&&v1>=1.25&&v5>=1.05&&b1>=.35&&t.c>0,ss=r1<0&&r5<0&&c1[c1.length-1]<e1&&R1<48&&R1>22&&v1>=1.25&&v5>=1.05&&b1>=.35&&t.c<0;
var ms=Math.round(Math.min(Math.abs(t.c)*4,20)+Math.min(v5*10,20)+(mb||vb?35:0)+(R5>=52&&R5<=78||R5<=48&&R5>=22?10:0)+(b5>=.35?10:0));
var sscr=Math.round(Math.min(Math.abs(r1)*5000,20)+Math.min(v1*16,30)+(sb||ss?30:0)+(v5>=1.05?10:0)+(b1>=.35?10:0));
var sig=ms>=72&&(mb||vb)?(mb?'BUY':'SELL'):sscr>=72&&(sb||ss)?(sb?'BUY':'SELL'):'WATCH';
return{signal:sig,score:Math.max(ms,sscr),mScore:ms,sScore:sscr,atr:a,spike:v1,spike5:v5,rsi5:R5,rsi1:R1,body:b1,momentum:mb?'BUY':vb?'SELL':'WAIT',scalp:sb?'BUY':ss?'SELL':'WAIT',trend5:l5>e21?'BULLISH':l5<e21?'BEARISH':'WAIT',trend15:l15>e15?'BULLISH':l15<e15?'BEARISH':'WAIT'}}
async function boot(){load();try{var e=await api('/fapi/v1/exchangeInfo');S.universe=(e.symbols||[]).filter(function(x){return x.contractType==='PERPETUAL'&&x.quoteAsset==='USDT'&&x.status==='TRADING'}).map(function(x){return x.symbol});var t=await api('/fapi/v1/ticker/24hr');(Array.isArray(t)?t:[]).forEach(function(x){if(S.universe.indexOf(x.symbol)>=0)S.ticks[x.symbol]={p:N(x.lastPrice),c:N(x.priceChangePercent),v:N(x.quoteVolume)}});S.universe.sort(function(a,b){return N(S.ticks[b]&&S.ticks[b].v)-N(S.ticks[a]&&S.ticks[a].v)});connect();await scan(true);await loadOptions()}catch(e){S.error=e.message;render()}}
function connect(){try{var ws=new WebSocket('wss://fstream.binance.com/stream');ws.onopen=function(){ws.send(JSON.stringify({method:'SUBSCRIBE',params:['!ticker@arr'],id:1}))};ws.onmessage=function(ev){try{var z=JSON.parse(ev.data),a=Array.isArray(z)?z:(z.data||[]);a.forEach(function(x){if(x&&x.s&&S.ticks[x.s])S.ticks[x.s]={p:N(x.c),c:N(x.P),v:N(x.q)}});manage();render()}catch(e){}};ws.onclose=function(){setTimeout(connect,4000)}}catch(e){setTimeout(connect,4000)}}
async function scan(first){if(busy||!S.universe.length)return;busy=true;var batch=[],size=first?30:24;if(first){for(var j=0;j<Math.min(size,S.universe.length);j++)batch.push(S.universe[j])}else{for(var i=0;i<size;i++)batch.push(S.universe[(cursor+i)%S.universe.length]);cursor=(cursor+size)%S.universe.length}await Promise.all(batch.map(async function(sym){try{var r=await Promise.all(['1m','5m','15m'].map(function(iv){return api('/fapi/v1/klines?symbol='+sym+'&interval='+iv+'&limit=50')}));S.kl[sym]={m1:r[0],m5:r[1],m15:r[2]};S.analysis[sym]=analyze(sym)}catch(e){}}));S.deep=Object.keys(S.kl).length;busy=false;engine();render()}
function rows(){return S.universe.map(function(sym){var a=S.analysis[sym],t=S.ticks[sym]||{};if(!a||!t.p)return null;return{symbol:sym,side:a.signal,score:a.score,mScore:a.mScore,sScore:a.sScore,atr:a.atr,p:t.p,c:t.c,spike:a.spike,spike5:a.spike5,rsi5:a.rsi5,rsi1:a.rsi1,momentum:a.momentum,scalp:a.scalp,trend5:a.trend5,trend15:a.trend15}}).filter(Boolean).sort(function(a,b){return b.score-a.score})}
function candidates(kind){return rows().filter(function(x){return kind==='M'?(x.momentum!=='WAIT'&&x.mScore>=72):(x.scalp!=='WAIT'&&x.sScore>=72)})}
function cooldown(sym,eng){var now=Date.now(),last=0;S.history.forEach(function(h){if(h.symbol===sym&&h.engine===eng)last=Math.max(last,N(h.time))});return now-last<15*60*1000}
function dailyLossStop(){var d=new Date().toDateString(),loss=0;S.history.forEach(function(h){if(new Date(N(h.time)).toDateString()===d&&N(h.pnl)<0)loss+=N(h.pnl)});return loss<=-(Math.max(S.equity,1)*Math.abs(DAILY))}
function open(c,eng){if(!c||dailyLossStop()||cooldown(c.symbol,eng)||S.positions.some(function(p){return p.symbol===c.symbol&&p.engine===eng}))return false;var px=c.p,risk=S.equity*(S.risk/100),stop=eng==='SCALPING'?Math.max(c.atr/Math.max(px,1e-9)*.65,.003):Math.max(c.atr/Math.max(px,1e-9)*1.15,.007),sl=c.side==='BUY'?px*(1-stop):px*(1+stop),tp=c.side==='BUY'?px*(1+stop*2.2):px*(1-stop*2.2),qty=risk/Math.max(px*stop,1e-9),fee=px*qty*FEE;S.positions.push({id:Date.now()+Math.random(),symbol:c.symbol,side:c.side,entry:px,current:px,qty:qty,sl:sl,tp:tp,risk:risk,engine:eng,opened:Date.now(),kind:'FUTURES',entryFee:fee,exitFee:0,fees:fee});save();return true}
function engine(){if(!S.auto)return;var m=S.positions.filter(function(p){return p.engine==='MOMENTUM'}).length,s=S.positions.filter(function(p){return p.engine==='SCALPING'}).length;var mc=candidates('M'),sc=candidates('S');for(var i=0;i<mc.length&&m<MAXM;i++){var c=mc[i];if(open({symbol:c.symbol,side:c.momentum,p:c.p,atr:c.atr},'MOMENTUM'))m++}for(var j=0;j<sc.length&&s<MAXS;j++){var d=sc[j];if(open({symbol:d.symbol,side:d.scalp,p:d.p,atr:d.atr},'SCALPING'))s++}autoOptions()}
function base(x){return String(x||'').toUpperCase().replace(/[-_]/g,'').replace(/USDT$/,'')}
async function loadOptions(){if(optBusy)return;optBusy=true;try{var e=await api('/eapi/v1/exchangeInfo'),a=e.optionSymbols||e.symbols||[];S.opt=a.filter(function(o){return o.status==='TRADING'||o.symbolStatus==='TRADING'});var mk=await api('/eapi/v1/mark');S.marks={};(Array.isArray(mk)?mk:[]).forEach(function(x){S.marks[x.symbol]=N(x.markPrice||x.price||x.bidPrice||x.askPrice)});autoOptions()}catch(e){S.error='Options: '+e.message}optBusy=false;render()}
function oi(o){var n=String(o.symbol||o.optionSymbol||''),b=base(o.underlying||o.underlyingSymbol||n.split('-')[0]),t=String(o.side||o.optionType||'').toUpperCase();if(t==='C')t='CALL';if(t==='P')t='PUT';if(!t){var z=n.split('-').pop().toUpperCase();t=z==='C'?'CALL':z==='P'?'PUT':''}return{base:b,type:t,name:n,strike:N(o.strike),expiry:N(o.expiryDate||o.expiry||o.expirationDate)}}
function optionCandidates(){return rows().filter(function(x){return(x.side==='BUY'||x.side==='SELL')&&x.score>=72}).map(function(c){var want=c.side==='BUY'?'CALL':'PUT',o=S.opt.map(oi).filter(function(x){return x.base===base(c.symbol)&&x.type===want&&S.marks[x.name]>0});o.sort(function(a,b){return Math.abs(a.strike-c.p)-Math.abs(b.strike-c.p)});return o[0]?{coin:c.symbol,type:want,option:o[0],premium:S.marks[o[0].name],score:c.score,side:c.side}:null}).filter(Boolean).sort(function(a,b){return b.score-a.score})}
function autoOptions(){if(!S.auto)return;var count=S.positions.filter(function(p){return p.engine==='OPTIONS'}).length;if(count>=MAXO||!S.opt.length||dailyLossStop())return;var cs=optionCandidates();for(var i=0;i<cs.length&&count<MAXO;i++){var c=cs[i],name=c.option.name;if(S.positions.some(function(p){return p.symbol===name})||cooldown(name,'OPTIONS'))continue;var px=c.premium,risk=S.equity*(S.risk/100),qty=Math.max(1,Math.floor(risk/Math.max(px*.35,1e-9))),fee=px*qty*FEE;S.positions.push({id:Date.now()+Math.random(),symbol:name,side:'BUY',entry:px,current:px,qty:qty,sl:px*.68,tp:px*1.65,risk:risk,engine:'OPTIONS',opened:Date.now(),kind:'OPTION',underlying:c.coin,optionType:c.type,entryFee:fee,exitFee:0,fees:fee,score:c.score});count++}save()}
async function optionPrices(){var ops=S.positions.filter(function(p){return p.kind==='OPTION'});if(!ops.length)return;try{var mk=await api('/eapi/v1/mark'),m={};(Array.isArray(mk)?mk:[]).forEach(function(x){m[x.symbol]=N(x.markPrice||x.price||x.bidPrice||x.askPrice)});ops.forEach(function(p){if(m[p.symbol]>0)p.current=m[p.symbol]});manage()}catch(e){}}
function manage(){var changed=false;S.positions.slice().forEach(function(p){var px=p.kind==='OPTION'?N(p.current):N(S.ticks[p.symbol]&&S.ticks[p.symbol].p);if(!px)return;p.current=px;var gross=p.side==='BUY'?(px-p.entry)*p.qty:(p.entry-px)*p.qty,ef=px*p.qty*FEE;p.exitFee=ef;p.fees=N(p.entryFee)+ef;p.pnl=gross-p.fees;var hit=p.side==='BUY'?(px<=p.sl||px>=p.tp):(px>=p.sl||px<=p.tp);if(hit){S.realized+=p.pnl;S.equity+=p.pnl;S.fees+=p.fees;S.history.push({time:Date.now(),symbol:p.symbol,side:p.side,engine:p.engine,entry:p.entry,exit:px,pnl:p.pnl,fees:p.fees,result:p.pnl>=0?'WIN':'LOSS'});S.positions=S.positions.filter(function(x){return x.id!==p.id});changed=true}});if(changed){save();setTimeout(engine,300)}}
function nav(){return['overview','momentum','scalping','positions','history','options','settings'].map(function(x){return'<button class="'+(S.tab===x?'active':'')+'" onclick="tab(\''+x+'\')">'+x.toUpperCase()+'</button>'}).join('')}
function table(kind){var a=rows();if(kind==='M')a=a.filter(function(x){return x.momentum!=='WAIT'});if(kind==='S')a=a.filter(function(x){return x.scalp!=='WAIT'});return'<div class="tablewrap"><table><tr><th>#</th><th>COIN</th><th>PRICE</th><th>24H</th><th>M</th><th>S</th><th>VOL 1m</th><th>RSI</th><th>SIGNAL</th></tr>'+a.slice(0,30).map(function(x,i){var side=kind==='M'?x.momentum:kind==='S'?x.scalp:x.side;return'<tr><td>'+(i+1)+'</td><td><b>'+E(x.symbol)+'</b></td><td>'+x.p+'</td><td class="'+(x.c>=0?'buy':'sell')+'">'+Pct(x.c)+'</td><td>'+x.mScore+'</td><td>'+x.sScore+'</td><td>'+N(x.spike).toFixed(2)+'x</td><td>'+N(x.rsi1).toFixed(0)+'</td><td class="'+(side==='BUY'?'buy':side==='SELL'?'sell':'watch')+'">'+side+'</td></tr>}).join('')+'</table></div>'}
function optTable(){var a=optionCandidates();return'<div class="notice">Option symbols: <b>'+S.opt.length+'</b> · eligible coins: <b>'+a.length+'</b> · strong threshold ≥72 · CALL on bullish, PUT on bearish · paper only.</div><div class="tablewrap"><table><tr><th>#</th><th>COIN</th><th>TYPE</th><th>OPTION</th><th>PREMIUM</th><th>SCORE</th></tr>'+a.slice(0,30).map(function(x,i){return'<tr><td>'+(i+1)+'</td><td><b>'+E(x.coin)+'</b></td><td class="'+(x.type==='CALL'?'buy':'sell')+'">'+x.type+'</td><td>'+E(x.option.name)+'</td><td>'+x.premium+'</td><td>'+x.score+'</td></tr>'}).join('')+'</table></div>'}
function positions(){return'<div class="positions">'+(S.positions.length?S.positions.map(function(p){return'<div class="pos"><b>'+E(p.symbol)+'</b> · '+p.engine+'<div class="kv"><span>Entry</span><b>'+N(p.entry).toFixed(6)+'</b></div><div class="kv"><span>Current</span><b>'+N(p.current).toFixed(6)+'</b></div><div class="kv"><span>Net P&L</span><b class="'+(N(p.pnl)>=0?'buy':'sell')+'">'+M(p.pnl)+'</b></div><div class="kv"><span>Fees</span><b>'+M(p.fees)+'</b></div><div class="kv"><span>SL / TP</span><b>'+N(p.sl).toFixed(6)+' / '+N(p.tp).toFixed(6)+'</b></div></div>'}).join(''):'<div class="notice">No open paper positions.</div>')+'</div>'}
function history(){var a=S.history.slice().reverse();return'<div class="tablewrap"><table><tr><th>TIME</th><th>COIN</th><th>ENGINE</th><th>ENTRY</th><th>EXIT</th><th>FEES</th><th>NET P&L</th><th>RESULT</th></tr>'+a.slice(0,100).map(function(x){return'<tr><td>'+new Date(N(x.time)).toLocaleString('en-IN')+'</td><td>'+E(x.symbol)+'</td><td>'+x.engine+'</td><td>'+N(x.entry).toFixed(6)+'</td><td>'+N(x.exit).toFixed(6)+'</td><td>'+M(x.fees)+'</td><td class="'+(N(x.pnl)>=0?'buy':'sell')+'">'+M(x.pnl)+'</td><td>'+x.result+'</td></tr>'}).join('')+'</table></div>'}
function render(){var el=document.getElementById('app');if(!el)return;var open=S.positions.length,un=S.positions.filter(function(p){return p.engine==='MOMENTUM'}).length,us=S.positions.filter(function(p){return p.engine==='SCALPING'}).length,uo=S.positions.filter(function(p){return p.engine==='OPTIONS'}).length;var content=S.tab==='overview'?table():S.tab==='momentum'?table('M'):S.tab==='scalping'?table('S'):S.tab==='positions'?positions():S.tab==='history'?history():S.tab==='options'?optTable():'<div class="notice">Strong engine: Momentum 5m+15m trend/EMA/RSI/volume confirmation; Scalping 1m+5m impulse/volume/body confirmation; 15m cooldown; daily loss guard; options require score ≥72. Taker fee simulation 0.05% per side. Real orders remain locked.</div>';
el.innerHTML='<div class="app"><div class="top"><div><div class="brand">⚡ BINANCE COMMAND CENTER</div><div class="muted">PAPER · LIVE MARKET FEED · '+(S.error?'ERROR':'STREAM OK')+'</div></div><div class="controls"><button onclick="toggleAuto()">AUTO '+(S.auto?'ON':'OFF')+'</button></div></div><div class="grid"><div class="card">EQUITY<div class="metric">'+M(S.equity)+'</div></div><div class="card">REALIZED NET P&L<div class="metric">'+M(S.realized)+'</div></div><div class="card">TOTAL FEES<div class="metric">'+M(S.fees)+'</div></div><div class="card">COINS / ANALYSED<div class="metric">'+S.universe.length+' / '+S.deep+'</div></div></div><div class="engine"><div class="card">MOMENTUM<div class="metric">'+un+'/'+MAXM+'</div></div><div class="card">SCALPING<div class="metric">'+us+'/'+MAXS+'</div></div><div class="card">OPTIONS<div class="metric">'+uo+'/'+MAXO+'</div></div><div class="card">TOTAL<div class="metric">'+open+'/10</div></div></div><div class="nav">'+nav()+'</div>'+(S.error?'<div class="notice" style="color:#ff6075">'+E(S.error)+'</div>':'')+'<div class="panel"><h3>'+ (S.tab==='options'?'Options Scanner':S.tab==='settings'?'Strong Risk Engine':'All-Coin Scanner')+'</h3>'+content+'</div><div class="muted" style="margin-top:10px">Visible top 30 · remaining coins continue scanning in background · Binance taker fee simulation 0.05%/side · paper only · real orders locked.</div></div>'}
window.tab=function(x){S.tab=x;render()};window.toggleAuto=function(){S.auto=!S.auto;render();if(S.auto)engine()};window.setRisk=function(x){S.risk=N(x);save();render()};window.resetPaper=function(){S.positions=[];S.history=[];S.equity=10000;S.realized=0;S.fees=0;save();render()};
load();render();boot();setInterval(function(){scan(false)},20000);setInterval(function(){optionPrices()},15000);setInterval(function(){manage();render()},5000);
})();