const API='https://fapi.binance.com';
const START=10000,KEY='binanceScannerPaperV2',RISK_PCT=.01,DAILY_LOSS=300,LOSS_STREAK=3,MAX_OPEN_PER_ENGINE=3;
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{equity:START,trades:[],positions:[],paperEnabled:true};let tickers=[],busy=false;
const $=id=>document.getElementById(id),money=x=>'₹'+Number(x||0).toLocaleString('en-IN',{maximumFractionDigits:2}),num=x=>Number(x)||0;
function todayKey(){return new Date().toISOString().slice(0,10)}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderPaper()}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function candles(symbol,interval,limit=50){return json(`${API}/fapi/v1/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`)}
function ema(a,n){if(a.length<n)return num(a.at(-1));let k=2/(n+1),e=a.slice(0,n).reduce((s,x)=>s+x,0)/n;for(let i=n;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=7){if(a.length<=n)return 50;let g=0,l=0;for(let i=1;i<=n;i++){let d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){let d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al===0?100:100-100/(1+ag/al)}
function riskStatus(){let today=state.trades.filter(t=>new Date(t.closedAt).toISOString().slice(0,10)===todayKey());let daily=today.reduce((s,t)=>s+num(t.pnl),0),streak=0;for(const t of state.trades){if(new Date(t.closedAt).toISOString().slice(0,10)!==todayKey())break;if(num(t.pnl)<0)streak++;else break}return{daily,streak,blocked:daily<=-DAILY_LOSS||streak>=LOSS_STREAK}}
function volumeRatio(ks){let closed=ks.slice(0,-1),v=closed.map(x=>+x[5]),last=v.at(-1)||0,avg=v.slice(-21,-1).reduce((s,x)=>s+x,0)/Math.max(1,v.slice(-21,-1).length);return avg?last/avg:1}
function signalFor(t,fast,confirm){let price=num(t.lastPrice),change=num(t.priceChangePercent),vol=num(t.quoteVolume);return Promise.all([candles(t.symbol,fast),candles(t.symbol,confirm)]).then(([a,b])=>{let c=a.map(x=>+x[4]),cc=b.map(x=>+x[4]),e5=ema(c,5),e13=ema(c,13),r=rsi(c,7),ce5=ema(cc,5),ce13=ema(cc,13),vr=volumeRatio(a),last=a.at(-2),o=+last[1],h=+last[2],l=+last[3],cl=+last[4],range=Math.max(h-l,1e-12),body=Math.abs(cl-o)/range,bull=cl>o,bear=cl<o;
let trendLong=e5>e13&&ce5>ce13,trendShort=e5<e13&&ce5<ce13,confirmLong=trendLong&&r>55&&bull,confirmShort=trendShort&&r<45&&bear;
let momentum=Math.min(25,Math.abs(change)*4),rsiScore=Math.min(15,Math.abs(r-50)*.5),volScore=vr>=1.5?15:vr>=1.2?9:0,candleScore=body>=.55?8:0,score=Math.round(Math.min(99,35+momentum+rsiScore+volScore+candleScore));
let long=confirmLong,short=confirmShort;if(Math.abs(change)<num($('minChange').value)||score<num($('minScore').value)||(!long&&!short)||body<.25)return null;
let side=long?'LONG':'SHORT',slPct=fast==='5m'?.01:.005,tpPct=fast==='5m'?.02:.01,sl=side==='LONG'?price*(1-slPct):price*(1+slPct),tp=side==='LONG'?price*(1+tpPct):price*(1-tpPct);
return{symbol:t.symbol,price,change,vol,side,score,sl,tp,vr,body,engine:fast==='5m'?'Momentum':'Scalping',reason:`${side==='LONG'?'Bullish':'Bearish'} EMA + ${fast}/${confirm} trend confirmation + RSI ${r.toFixed(1)} + volume ${vr.toFixed(1)}x${body>=.55?' + strong candle':''}`}})}
async function scan(){if(busy)return;busy=true;$('connection').textContent='Scanning Binance…';try{tickers=await json(`${API}/fapi/v1/ticker/24hr`);let us=tickers.filter(t=>t.symbol.endsWith('USDT')&&num(t.quoteVolume)>1000000).sort((a,b)=>num(b.quoteVolume)-num(a.quoteVolume)).slice(0,30);$('coinCount').textContent=us.length;$('market').textContent='Binance Futures';let mode=$('mode').value,fast=mode==='momentum'?'5m':'1m',confirm=mode==='momentum'?'15m':'5m',out=[];for(const t of us){try{let s=await signalFor(t,fast,confirm);if(s)out.push(s)}catch(e){}}out.sort((a,b)=>b.score-a.score);renderSignals(out);$('signalCount').textContent=out.length;$('updated').textContent='Updated '+new Date().toLocaleTimeString();$('connection').textContent='Live • Binance';updatePositions()}catch(e){$('connection').textContent='Market error';$('signals').innerHTML=`<tr><td colspan="11" class="empty">Binance data unavailable: ${e.message}</td></tr>`}finally{busy=false}}
function renderSignals(list){$('signals').innerHTML=list.length?list.map(s=>`<tr><td><b>${s.symbol.replace('USDT','/USDT')}</b></td><td>${s.price}</td><td class="${s.change>=0?'long':'short'}">${s.change.toFixed(2)}%</td><td>${(s.vol/1e6).toFixed(1)}M<br><small>${s.vr.toFixed(1)}x</small></td><td class="${s.side==='LONG'?'long':'short'}">${s.side}</td><td class="score">${s.score}</td><td>${s.price}</td><td>${s.sl.toFixed(6)}</td><td>${s.tp.toFixed(6)}</td><td>${s.reason}</td><td><button class="signalBtn" onclick='paperOpen(${JSON.stringify(s)})'>Paper Entry</button></td></tr>`).join(''):'<tr><td colspan="11" class="empty">No qualifying signals right now.</td></tr>'}
window.paperOpen=s=>{if(!state.paperEnabled)return alert('Paper Trading is OFF. Turn it ON first.');let risk=riskStatus();if(risk.blocked)return alert(`Risk Guard BLOCKED: daily P&L ${money(risk.daily)}, loss streak ${risk.streak}.`);let openEngine=state.positions.filter(p=>p.engine===s.engine).length;if(openEngine>=MAX_OPEN_PER_ENGINE)return alert(`Risk Guard: maximum ${MAX_OPEN_PER_ENGINE} open ${s.engine} positions reached.`);if(state.positions.some(p=>p.symbol===s.symbol))return alert('Position already open for '+s.symbol);let equity=START+state.trades.reduce((a,t)=>a+num(t.pnl),0),riskAmt=Math.max(0,equity*RISK_PCT),dist=Math.abs(s.price-s.sl),riskQty=dist?riskAmt/dist:0,capitalQty=s.price?equity/s.price:0,qty=Math.max(0,Math.min(riskQty,capitalQty));if(qty<=0)return alert('Invalid paper position size.');state.positions.push({...s,entry:s.price,qty,openedAt:Date.now()});save()}
function updatePositions(){let changed=false;state.positions=state.positions.filter(p=>{let t=tickers.find(x=>x.symbol===p.symbol);if(!t)return true;let px=num(t.lastPrice),pnl=p.side==='LONG'?(px-p.entry)*p.qty:(p.entry-px)*p.qty;p.unreal=pnl;let hit=p.side==='LONG'?(px<=p.sl||px>=p.tp):(px>=p.sl||px<=p.tp);if(hit){let exit=px,final=p.side==='LONG'?(exit-p.entry)*p.qty:(p.entry-exit)*p.qty;state.equity+=final;state.trades.unshift({...p,exit,pnl:final,closedAt:Date.now()});changed=true;return false}return true});if(changed)save();else renderPaper()}
function renderPaper(){let realised=state.trades.reduce((s,t)=>s+num(t.pnl),0),unreal=state.positions.reduce((s,p)=>s+num(p.unreal),0),risk=riskStatus();$('equity').textContent=money(START+realised+unreal);$('realised').textContent=money(realised);$('openCount').textContent=state.positions.length;$('positions').innerHTML=state.positions.length?state.positions.map(p=>`<div class="pos"><h3 class="${p.side==='LONG'?'long':'short'}">${p.symbol} ${p.side}</h3><p>${p.engine} • Qty ${p.qty.toFixed(6)} • Entry ${p.entry}</p><p>SL ${p.sl.toFixed(6)} • TP ${p.tp.toFixed(6)} • Unrealised <b>${money(p.unreal)}</b></p><p>${p.reason}</p></div>`).join(''):'<p class="empty">No open positions.</p>';let wins=state.trades.filter(t=>num(t.pnl)>0).length,rate=state.trades.length?wins/state.trades.length*100:0;$('stats').textContent=`${state.trades.length} trades • ${rate.toFixed(1)}% win rate`;$('trades').innerHTML=state.trades.slice(0,30).map(t=>`<tr><td>${new Date(t.closedAt).toLocaleTimeString()}</td><td>${t.symbol}</td><td class="${t.side==='LONG'?'long':'short'}">${t.side}</td><td>${t.entry}</td><td>${t.exit}</td><td class="${t.pnl>=0?'long':'short'}">${money(t.pnl)}</td><td>${t.reason}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No completed trades.</td></tr>';$('riskState').textContent=risk.blocked?'BLOCKED':'SAFE';$('riskState').className=risk.blocked?'dangerText':'safe';$('dailyLoss').textContent=`₹${DAILY_LOSS}`;$('lossStreak').textContent=LOSS_STREAK;$('paperState').textContent=state.paperEnabled?'ON':'OFF'}
$('paperBtn').onclick=()=>{state.paperEnabled=!state.paperEnabled;save()};$('refreshBtn').onclick=scan;$('mode').onchange=scan;$('minChange').onchange=scan;$('minScore').onchange=scan;$('resetBtn').onclick=()=>{if(confirm('Reset all paper trades and positions?')){state={equity:START,trades:[],positions:[],paperEnabled:true};save()}};renderPaper();scan();setInterval(scan,60000);setInterval(updatePositions,10000);