(()=>{'use strict';
const KEY='ddMode';
function patch(src){
 const testnet="localStorage.getItem('ddMode')==='TESTNET'";
 src=src.replace("const PUB='/api/binance-market?path=',AC='/api/binance-account?path=',TR='/api/binance-trade'","const PUB='/api/binance-market?path=',AC=("+testnet+"?'/api/binance-testnet-account?path=':'/api/binance-account?path='),TR=("+testnet+"?'/api/binance-testnet-trade':'/api/binance-trade')");
 src=src.replace(/const S=\{mode:'PAPER',auto:true,liveAuto:false/,"const S={mode:(localStorage.getItem('ddMode')||'PAPER'),auto:true,liveAuto:false");
 src=src.replace(/function paperOpen\(x,e\)\{[\s\S]*?\nasync function liveOpen/,"function paperOpen(x,e){if(!['PAPER','TESTNET'].includes(S.mode)||!canOpen(x,e))return false;const z=signal(x,e),r=riskModel(x,e,S.eq),ef=x.p*r.q*F;if(!Number.isFinite(r.q)||r.q<=0)return false;S.pos.push({id:Date.now()+Math.random(),s:x.s,e,side:z,entry:x.p,current:x.p,q:r.q,sl:z==='BUY'?x.p*(1-r.stop):x.p*(1+r.stop),tp:z==='BUY'?x.p*(1+2*r.stop):x.p*(1-2*r.stop),entryFee:ef,pnl:-ef,feeRate:F,mode:S.mode,reason:x.reasons,opened:Date.now()});S.lastTrade[x.s]=Date.now();S.hist.unshift({time:Date.now(),s:x.s,e,side:z,action:'ENTRY',price:x.p,qty:r.q,pnl:0,fees:ef,live:false,reason:x.reasons});save();return true}\nasync function liveOpen");
 src=src.replace(/function engine\(\)\{[\s\S]*?\nfunction managePaper/,"function engine(){if(!S.auto)return;const arr=S.rows.filter(x=>x&&(signal(x,'MOMENTUM')!=='WAIT'||signal(x,'SCALPING')!=='WAIT')).sort((a,b)=>Math.max(b.m,b.sc)-Math.max(a.m,a.sc));for(const x of arr){if(S.mode==='PAPER'||S.mode==='TESTNET'){if(signal(x,'MOMENTUM')!=='WAIT'&&S.pos.filter(p=>p.e==='MOMENTUM').length<MC)paperOpen(x,'MOMENTUM');if(signal(x,'SCALPING')!=='WAIT'&&S.pos.filter(p=>p.e==='SCALPING').length<SC)paperOpen(x,'SCALPING')}else if(S.mode==='LIVE'&&S.liveAuto){if(x.m>=78&&signal(x,'MOMENTUM')!=='WAIT'&&S.pos.filter(p=>p.e==='MOMENTUM').length<MC)liveOpen(x,'MOMENTUM');if(x.sc>=78&&signal(x,'SCALPING')!=='WAIT'&&S.pos.filter(p=>p.e==='SCALPING').length<SC)liveOpen(x,'SCALPING')}}}\nfunction managePaper");
 src=src.replace(/function managePaper\(\)\{for\(const p of \[\.\.\.S\.pos\]\)\{if\(p\.mode!==['"]PAPER['"]\)continue;/,"function managePaper(){for(const p of [...S.pos]){if(!['PAPER','TESTNET'].includes(p.mode))continue;");
 src=src.replace(/async function syncAccount\(\)\{if\(Date\.now\(\)-S\.lastAccount<2500\)return;/,"async function syncAccount(){if(S.mode==='TESTNET'){S.account=null;S.err='';return;}if(Date.now()-S.lastAccount<2500)return;");
 src=src.replace("S.err='Account sync: '+e.message","S.err=(S.mode==='PAPER'||S.mode==='TESTNET'?'':'Account sync: '+e.message)");
 src=src.replace("const q=JSON.parse(localStorage.ddv5||'{}')","const q=JSON.parse(localStorage['ddv5_'+(localStorage.getItem('ddMode')||'PAPER')]||'{}')");
 src=src.replace("localStorage.ddv5=JSON.stringify","localStorage['ddv5_'+(S.mode||'PAPER')]=JSON.stringify");
 src=src.replace("S.mode==='LIVE'?'LIVE MODE · Binance account sync active.':'PAPER MODE · Real orders are OFF.'","S.mode==='LIVE'?'LIVE MODE · Binance account sync active.':S.mode==='TESTNET'?'TESTNET · LOCAL SIMULATION · Real orders are OFF.':'PAPER MODE · Real orders are OFF.'");
 return src;
}
function controls(){const root=document.getElementById('dd-mode-root');if(!root)return;root.innerHTML='';const current=localStorage.getItem(KEY)||'PAPER';['PAPER','TESTNET','LIVE'].forEach(m=>{const b=document.createElement('button');b.type='button';b.textContent=m+(m===current?' ✓':'');b.dataset.mode=m;b.style.cssText='background:'+(m===current?'#15304b':'#0d1a2a')+';color:#e9f1fb;border:1px solid '+(m===current?'#4da3ff':'#2a415b')+';border-radius:10px;padding:9px 13px;cursor:pointer;font-weight:800';b.onclick=()=>{if(m===current)return;if(m==='LIVE'&&!confirm('LIVE mode selected. Real Binance orders remain server-locked until LIVE_UNLOCKED=true. Continue?'))return;localStorage.setItem(KEY,m);location.reload()};root.appendChild(b)});const note=document.createElement('span');note.id='dd-mode-note';note.style.cssText='font-size:11px;color:#8295ad;margin-left:4px';note.textContent=current==='PAPER'?'Local paper simulation':current==='TESTNET'?'TESTNET · local simulation fallback (Binance Demo private API is region-restricted)':'Binance LIVE · real orders locked by server';root.appendChild(note)}
function forceTestnetUI(){if((localStorage.getItem(KEY)||'PAPER')!=='TESTNET')return;document.querySelectorAll('body *').forEach(el=>{if(el.children.length)return;const t=el.textContent||'';if(t.includes('PAPER MODE · Real orders are OFF.'))el.textContent=t.replace(/PAPER MODE · Real orders are OFF\./g,'TESTNET · LOCAL SIMULATION · Real orders are OFF.');if(t==='AUTO LIVE ON')el.textContent='AUTO TESTNET ON';if(t==='AUTO LIVE OFF')el.textContent='AUTO TESTNET OFF'});const n=document.getElementById('dd-mode-note');if(n)n.textContent='TESTNET · local simulation fallback (Binance Demo private API is region-restricted)'}
async function boot(){try{controls();const r=await fetch('/app-scanner-v3.js?mode='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Scanner source failed '+r.status);let src=await r.text();src=patch(src);(0,eval)(src);controls();forceTestnetUI();setInterval(forceTestnetUI,500);new MutationObserver(forceTestnetUI).observe(document.body,{subtree:true,childList:true,characterData:true});}catch(e){const a=document.getElementById('app');if(a)a.innerHTML='<div style="padding:30px"><b>Scanner startup error</b><div style="color:#ff6178;margin-top:8px">'+String(e.message||e)+'</div></div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();