(()=>{'use strict';
const KEY='ddMode';
function patch(src){
 const testnet="localStorage.getItem('ddMode')==='TESTNET'";
 src=src.replace("const PUB='/api/binance-market?path=',AC='/api/binance-account?path=',TR='/api/binance-trade'","const PUB='/api/binance-market?path=',AC=("+testnet+"?'/api/binance-testnet-account?path=':'/api/binance-account?path='),TR=("+testnet+"?'/api/binance-testnet-trade':'/api/binance-trade')");
 src=src.replace("mode:'PAPER',auto:true,liveAuto:false","mode:(localStorage.getItem('ddMode')||'PAPER'),auto:true,liveAuto:(localStorage.getItem('ddMode')==='TESTNET')");
 src=src.replace("if(S.mode!=='PAPER'||!canOpen(x,e))return false;","if(!['PAPER','TESTNET'].includes(S.mode)||!canOpen(x,e))return false;");
 src=src.replace("feeRate:F,mode:'PAPER'","feeRate:F,mode:S.mode");
 /* TESTNET uses the proven local paper execution path. Do not call Binance private APIs. */
 src=src.replace(/function engine\(\)\{[\s\S]*?\}\nfunction managePaper/,"function engine(){if(!S.auto&&S.mode!=='TESTNET')return;const arr=S.rows.filter(x=>x&&(x.m>=65||x.sc>=65)).sort((a,b)=>Math.max(b.m,b.sc)-Math.max(a.m,a.sc));for(const x of arr){if(S.mode==='PAPER'||S.mode==='TESTNET'){if(x.m>=65&&S.pos.filter(p=>p.e==='MOMENTUM').length<MC)paperOpen(x,'MOMENTUM');if(x.sc>=65&&S.pos.filter(p=>p.e==='SCALPING').length<SC)paperOpen(x,'SCALPING')}else if(S.mode==='LIVE'&&S.liveAuto){if(x.m>=78&&S.pos.filter(p=>p.e==='MOMENTUM').length<MC)liveOpen(x,'MOMENTUM');if(x.sc>=78&&S.pos.filter(p=>p.e==='SCALPING').length<SC)liveOpen(x,'SCALPING')}}}\nfunction managePaper");
 src=src.replace("function managePaper(){for(const p of [...S.pos]){if(p.mode!=='PAPER')continue;","function managePaper(){for(const p of [...S.pos]){if(!['PAPER','TESTNET'].includes(p.mode))continue;");
 src=src.replace("async function syncAccount(){if(Date.now()-S.lastAccount<2500)return;","async function syncAccount(){if(S.mode==='TESTNET'){S.account=null;S.err='';return;}if(Date.now()-S.lastAccount<2500)return;");
 src=src.replace("S.err=(S.mode==='PAPER'?'':('Account sync: '+e.message))","S.err=(S.mode==='PAPER'||S.mode==='TESTNET'?'':('Account sync: '+e.message))");
 src=src.replace("if(!['LIVE','TESTNET'].includes(S.mode)||!S.liveAuto)","if(S.mode!=='LIVE'||!S.liveAuto)");
 src=src.replace("else if((S.mode==='LIVE'||S.mode==='TESTNET')&&S.liveAuto)","else if(S.mode==='LIVE'&&S.liveAuto)");
 src=src.replace("if(S.mode==='LIVE'||S.mode==='TESTNET')","if(S.mode==='LIVE')");
 src=src.replace("e:S.mode,side:N(p.positionAmt)>0?'BUY':'SELL'","e:'LIVE',side:N(p.positionAmt)>0?'BUY':'SELL'");
 src=src.replace("mode:S.mode}))","mode:'LIVE'}))");
 src=src.replace("x.contractType==='PERPETUAL'&&x.quoteAsset==='USDT'&&x.status==='TRADING'","x.contractType==='PERPETUAL'&&x.quoteAsset==='USDT'&&x.status==='TRADING'&&/^[A-Z0-9_]{5,30}$/.test(x.symbol)");
 src=src.replace("if(p.mode==='PAPER'){","if(['PAPER','TESTNET'].includes(p.mode)){" );
 src=src.replace("const q=JSON.parse(localStorage.ddv5||'{}')","const q=JSON.parse(localStorage['ddv5_'+(localStorage.getItem('ddMode')||'PAPER')]||'{}')");
 src=src.replace("localStorage.ddv5=JSON.stringify","localStorage['ddv5_'+(S.mode||'PAPER')]=JSON.stringify");
 src=src.replace("S.mode==='LIVE'?'LIVE MODE · Binance account sync active.':'PAPER MODE · Real orders are OFF.'","S.mode==='LIVE'?'LIVE MODE · Binance account sync active.':S.mode==='TESTNET'?'TESTNET · LOCAL SIMULATION · Real orders are OFF.':'PAPER MODE · Real orders are OFF.'");
 return src;
}
function controls(){const root=document.getElementById('dd-mode-root');if(!root)return;root.innerHTML='';const current=localStorage.getItem(KEY)||'PAPER';['PAPER','TESTNET','LIVE'].forEach(m=>{const b=document.createElement('button');b.type='button';b.textContent=m+(m===current?' ✓':'');b.dataset.mode=m;b.style.cssText='background:'+(m===current?'#15304b':'#0d1a2a')+';color:#e9f1fb;border:1px solid '+(m===current?'#4da3ff':'#2a415b')+';border-radius:10px;padding:9px 13px;cursor:pointer;font-weight:800';b.onclick=()=>{if(m===current)return;if(m==='LIVE'&&!confirm('LIVE mode selected. Real Binance orders remain server-locked until LIVE_UNLOCKED=true. Continue?'))return;localStorage.setItem(KEY,m);location.reload()};root.appendChild(b)});const note=document.createElement('span');note.id='dd-mode-note';note.style.cssText='font-size:11px;color:#8295ad;margin-left:4px';note.textContent=current==='PAPER'?'Local paper simulation':current==='TESTNET'?'TESTNET · local simulation fallback (Binance Demo private API is region-restricted)':'Binance LIVE · real orders locked by server';root.appendChild(note)}
function forceTestnetUI(){const cur=localStorage.getItem(KEY)||'PAPER';if(cur!=='TESTNET')return;const replaceNode=(el)=>{if(!el||el.tagName==='SCRIPT'||el.tagName==='STYLE')return;const txt=(el.textContent||'').trim();if(txt.includes('PAPER MODE · Real orders are OFF.')){for(const n of el.childNodes){if(n.nodeType===3&&n.nodeValue.includes('PAPER MODE · Real orders are OFF.'))n.nodeValue=n.nodeValue.replace(/PAPER MODE · Real orders are OFF\./g,'TESTNET · LOCAL SIMULATION · Real orders are OFF.')}}};document.querySelectorAll('body *').forEach(replaceNode);document.querySelectorAll('button').forEach(b=>{const t=b.textContent.trim();if(t==='AUTO LIVE ON')b.textContent='AUTO TESTNET ON';if(t==='AUTO LIVE OFF')b.textContent='AUTO TESTNET OFF'});const n=document.getElementById('dd-mode-note');if(n)n.textContent='TESTNET · local simulation fallback (Binance Demo private API is region-restricted)';}
async function boot(){try{controls();const r=await fetch('/app-scanner-v3.js?mode='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Scanner source failed '+r.status);let src=await r.text();src=patch(src);(0,eval)(src);controls();forceTestnetUI();setInterval(forceTestnetUI,500);const mo=new MutationObserver(forceTestnetUI);mo.observe(document.body,{subtree:true,childList:true,characterData:true});}catch(e){const a=document.getElementById('app');if(a)a.innerHTML='<div style="padding:30px"><b>Scanner startup error</b><div style="color:#ff6178;margin-top:8px">'+String(e.message||e)+'</div></div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();