/* DealDost V7 hard stabilizer. Bypasses older fetch wrappers with direct XHR. */
(function(){
'use strict';
const API='https://fapi.binance.com',MAX=50,COIN_KEY='dealDostStableUniverseV7',RADAR_KEY='dealDostStableRadarV1';
const get=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(v)?v:d}catch(e){return d}};
const put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
let eligible=new Set();
function syncEligible(){if(eligible.size)return;if(Array.isArray(window.contracts)&&window.contracts.length)eligible=new Set(window.contracts.map(s=>s.symbol));}
function xhr(url){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('GET',url,true);x.timeout=9000;x.onload=()=>{try{if(x.status>=200&&x.status<300)resolve(JSON.parse(x.responseText));else reject(Error('HTTP '+x.status))}catch(e){reject(e)}};x.onerror=()=>reject(Error('Network error'));x.ontimeout=()=>reject(Error('Timeout'));x.send()})}
function choose(all){syncEligible();let stable=get(COIN_KEY,[]).filter(s=>eligible.has(s));const by=new Map(all.map(x=>[x.symbol,x]));stable=stable.filter(s=>by.has(s));const fresh=all.filter(x=>eligible.has(x.symbol)&&!stable.includes(x.symbol)).sort((a,b)=>Math.abs(Number(b.priceChangePercent)||0)-Math.abs(Number(a.priceChangePercent)||0));for(const x of fresh){if(stable.length>=MAX)break;stable.push(x.symbol)}stable=stable.slice(0,MAX);put(COIN_KEY,stable);window.__dealDostStableSymbols=stable.slice();return stable}
function ordered(all){const stable=choose(all),by=new Map(all.map(x=>[x.symbol,x]));return stable.map(s=>by.get(s)).filter(Boolean).slice(0,MAX)}
async function directTicker(){try{const all=await xhr(API+'/fapi/v1/ticker/24hr'),out=ordered(Array.isArray(all)?all:[]);return out}catch(e){return null}}
const native=window.fetch.bind(window);window.fetch=async function(input,init){const url=typeof input==='string'?input:(input?.url||'');if(/\/fapi\/v1\/exchangeInfo(?:\?|$)/.test(url)){try{const info=await xhr(API+'/fapi/v1/exchangeInfo');eligible=new Set((info.symbols||[]).filter(s=>s&&s.status==='TRADING'&&s.contractType==='PERPETUAL'&&(s.quoteAsset==='USDT'||s.quoteAsset==='USDC')&&/^[A-Z0-9]+$/.test(s.symbol)).map(s=>s.symbol));return new Response(JSON.stringify(info),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}catch(e){return native(input,init)}}if(/\/fapi\/v1\/ticker\/24hr(?:\?|$)/.test(url)){const out=await directTicker();if(out)return new Response(JSON.stringify(out),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}return native(input,init)};
function stableRadar(rows){const cards=[...document.querySelectorAll('.radarCard')];if(cards.length<4)return;const data=(rows||[]).filter(r=>r?.t?.symbol);const keys=['pump','dump','spike'];let radar=get(RADAR_KEY,{});const live=(key,score)=>{let list=(radar[key]||[]).filter(s=>data.some(r=>r.t.symbol===s));const candidates=data.slice().sort(score);for(const r of candidates){if(list.length>=5)break;if(!list.includes(r.t.symbol))list.push(r.t.symbol)}radar[key]=list.slice(0,5);return radar[key]};const pumps=live(keys[0],(a,b)=>Number(b.t.priceChangePercent)-Number(a.t.priceChangePercent));const dumps=live(keys[1],(a,b)=>Number(a.t.priceChangePercent)-Number(b.t.priceChangePercent));const spikes=live(keys[2],(a,b)=>Math.max(num(b.mom?.vr),num(b.scalp?.vr))-Math.max(num(a.mom?.vr),num(a.scalp?.vr)));put(RADAR_KEY,radar);const map=new Map(data.map(r=>[r.t.symbol,r]));const paint=(el,title,list,mode)=>{el.innerHTML='<small>'+title+'</small><ol>'+list.map(s=>{const r=map.get(s);if(!r)return '';const x=mode==='spike'?Math.max(num(r.mom?.vr),num(r.scalp?.vr)):num(r.t.priceChangePercent);return '<li><span>'+s+'</span><strong class="'+(mode==='spike'?'hot':x>=0?'up':'down')+'">'+(mode==='spike'?x.toFixed(2)+'x':(x>=0?'+':'')+x.toFixed(2)+'%')+'</strong></li>'}).join('')+'</ol>'};paint(cards[0],'TOP PUMP',pumps,'change');paint(cards[1],'TOP DUMP',dumps,'change');paint(cards[2],'VOLUME SPIKE',spikes,'spike');cards[3].innerHTML='<small>MIN SIGNAL SCORE</small><strong>'+(Number(document.getElementById('minScore')?.value)||75)+'/100</strong><span>5m + 15m confirmation required</span>'}
function num(v){return Number(v)||0}
window.renderRadar=stableRadar;
})();
