/* DealDost stable UI layer — V6 universe is the single source of truth. */
(function(){
'use strict';
const $=id=>document.getElementById(id),num=v=>Number(String(v??'').replace(/[^0-9.+-]/g,''))||0;
const MAX=50;
function symbols(){return Array.isArray(window.__dealDostStableSymbols)?window.__dealDostStableSymbols.slice(0,MAX):[]}
function arrange(){const body=$('signals');if(!body)return;const order=symbols();if(!order.length)return;const rows=[...body.querySelectorAll('tr')].filter(tr=>tr.querySelector('td'));const by=new Map(rows.map(tr=>[(tr.querySelector('td:nth-child(2)')?.textContent||'').trim(),tr]));const sorted=order.map(s=>by.get(s)).filter(Boolean);rows.forEach(tr=>{if(!sorted.includes(tr))sorted.push(tr)});if(rows.some((r,i)=>r!==sorted[i]))sorted.forEach(r=>body.appendChild(r))}
function decorate(){const body=$('signals');if(!body)return;arrange();const rows=[...body.querySelectorAll('tr')].filter(tr=>tr.querySelector('td'));const search=($('search')?.value||'').trim().toUpperCase().replace('/','');rows.forEach(tr=>{const td=tr.querySelectorAll('td'),symbol=(td[1]?.textContent||'').trim();tr.style.display=search&&symbol.toUpperCase().indexOf(search)<0?'none':'';tr.classList.add('scannerRow');if(td[3]){const ch=num(td[3].textContent);td[3].classList.remove('up','down');td[3].classList.add(ch>=0?'up':'down')}});const visible=rows.filter(tr=>tr.style.display!=='none'),info=$('scannerInfo');if(info)info.textContent=`${visible.length} stable coins · LIVE price/change/volume`;colorPnl()}
function colorPnl(){document.querySelectorAll('#momentumPositions td,#scalpPositions td,#trades td,#netPnl,#avgPnl').forEach(el=>{if(!/₹/.test(el.textContent))return;const v=num(el.textContent);el.classList.remove('pnlPositive','pnlNegative','pnlZero');el.classList.add(v>0?'pnlPositive':v<0?'pnlNegative':'pnlZero')})}
let observing=false;function observe(){const body=$('signals');if(!body||observing)return !!body;observing=true;new MutationObserver(()=>requestAnimationFrame(decorate)).observe(body,{childList:true,subtree:true});decorate();return true}if(!observe()){const t=setInterval(()=>{if(observe())clearInterval(t)},100)}$('search')?.addEventListener('input',()=>requestAnimationFrame(decorate));
/* Paper risk guard only; never touches market-data ordering. */
const GUARD_KEY='binancePaperRiskGuardV1',COOLDOWN=5*60*1000,LOSS_WINDOW=30*60*1000,LOSS_LIMIT=2,LOSS_LOCK=30*60*1000;let guard={};try{guard=JSON.parse(localStorage.getItem(GUARD_KEY)||'{}')||{}}catch(e){}
const saveGuard=()=>{try{localStorage.setItem(GUARD_KEY,JSON.stringify(guard))}catch(e){}};
function installRiskGuard(){if(typeof window.paperOpen!=='function'||window.__dealDostRiskGuard)return false;const original=window.paperOpen;window.__dealDostRiskGuard=true;window.paperOpen=function(s,auto=false){const symbol=s?.symbol,engine=s?.engine;if(!symbol||!engine)return original(s,auto);const key=symbol+'|'+engine,now=Date.now(),g=guard[key]||{};if(g.blockedUntil>now)return false;if(g.lastClose&&now-g.lastClose<COOLDOWN)return false;return original(s,auto)};return true}
let previousPositions=new Map();function monitor(){if(typeof state==='undefined'||!Array.isArray(state.positions))return;const current=new Map(state.positions.map(p=>[(p.symbol||'')+'|'+(p.engine||'')+'|'+(p.openedAt||0),p]));for(const [id,p] of previousPositions){if(current.has(id))continue;const key=(p.symbol||'')+'|'+(p.engine||'');if(!p.symbol||!p.engine)continue;const now=Date.now(),g=guard[key]||{};g.lastClose=now;const recent=Array.isArray(state.trades)?state.trades.slice().reverse().find(t=>t&&t.symbol===p.symbol&&t.engine===p.engine):null;const pnl=recent&&Number.isFinite(Number(recent.pnl))?Number(recent.pnl):Number(p.unreal||0);if(pnl<0){g.losses=Array.isArray(g.losses)?g.losses.filter(t=>t+LOSS_WINDOW>=now):[];g.losses.push(now);if(g.losses.length>=LOSS_LIMIT)g.blockedUntil=now+LOSS_LOCK}guard[key]=g}previousPositions=current;saveGuard()}
setInterval(()=>{installRiskGuard();monitor();arrange()},1000);
})();
