import 'dotenv/config';
import {Connection,PublicKey} from '@solana/web3.js';
import {createClient} from '@supabase/supabase-js';
const env=process.env as Record<string,string|undefined>;
const required=['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','SOLANA_RPC_HTTP','SOLANA_RPC_WS','PUMPFUN_PROGRAM_ID'];
for(const k of required) if(!env[k]) throw new Error(`Missing ${k}`);
const db=createClient(env.SUPABASE_URL!,env.SUPABASE_SERVICE_ROLE_KEY!);
const conn=new Connection(env.SOLANA_RPC_HTTP!,{wsEndpoint:env.SOLANA_RPC_WS!,commitment:'confirmed'});
const program=new PublicKey(env.PUMPFUN_PROGRAM_ID!);
const telegram=async(text:string)=>{if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return;await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text})})};
let seen=0;
conn.onLogs(program,async(log,ctx)=>{try{seen++;const tx=await conn.getParsedTransaction(log.signature,{maxSupportedTransactionVersion:0,commitment:'confirmed'});if(!tx?.meta)return;const mints=[...new Set((tx.meta.postTokenBalances??[]).map(x=>x.mint))];for(const mint of mints){await db.from('tokens').upsert({mint,last_seen_at:new Date().toISOString(),status:'unknown',score:0,raw:{signature:log.signature,slot:ctx.slot}},{onConflict:'mint'});await db.from('token_events').insert({mint,signature:log.signature,slot:ctx.slot,event_type:'unknown',raw:tx.meta});}if(seen%20===0)await db.from('scanner_heartbeats').update({status:'running',events_seen:seen,last_event_time:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',1);}catch(e){console.error(e)}} ,'confirmed');
console.log(`NOVA Pulse scanner listening: ${program.toBase58()}`);
