import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const TICKER='https://fapi.binance.com/fapi/v1/ticker/24hr',KLINES='https://fapi.binance.com/fapi/v1/klines',REFRESH=15000,START=10000;
const CFG={momentum:{entry:'5m',confirm:'15m',sl:.01,minSpike:2,minScore:75,minChange:2,cool:9e5,lockR:.25,trailMult:1.5,trailMin:.5,trailMax:1.2},scalp:{entry:'1m',confirm:'5m',sl:.005,minSpike:2,minScore:80,minChange:.5,cool:3e5,lockR:.2,trailMult:1,trailMin:.5,trailMax:1}};
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=v=>num(v).toLocaleString('en-US',{maximumFractionDigits:8});
const money=v=>Math.abs(num(v))>=1e9?'$'+(Math.abs(num(v))/1e9).toFixed(2)+'B':Math.abs(num(v))>=1e6?'$'+(Math.abs(num(v))/1e6).toFixed(2)+'M':Math.abs(num(v))>=1e3?'$'+(Math.abs(num(v))/1e3).toFixed(1)+'K':'$'+Math.abs(num(v)).toFixed(0);
const keyFor=(engine,symbol)=>`deal-${engine}-${symbol}`;
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('Binance API HTTP '+r.status);return r.json()}
async function candles(symbol,interval,limit=30){const j=await getJSON(`${KLINES}?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=${limit}`);return Array.isArray(j)?j:[]}
function atr(k,p=14){if(k.length<p+1)return 0;const x=k.slice(-(p+1));let s=0;for(let i=1;i<x.length;i++){const h=num(x[i][2]),l=num(x[i][3]),pc=num(x[i-1][4]);s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/p}
function trend(k){const c=k.map(x=>num(x[4])).filter(Boolean);if(c.length<6)return{t:'WAIT',e:0,last:0,prev:0};const p=Math.min(8,c.length),a=2/(p+1);let e=c[0];for(let i=1;i<c.length;i++)e=c[i]*a+e*(1-a);const last=c.at(-1),prev=c.at(-2);return{t:last>prev&&last>e?'BULLISH':last<prev&&last<e?'BEARISH':'WAIT',e,last,prev}}
function enrich(k1,k5,k15){const a=trend(k1),b=trend(k5),c=trend(k15),v1=k1.map(x=>num(x[5])),v5=k5.map(x=>num(x[5])),avg=x=>x.length?x.reduce((s,n)=>s+n,0)/x.length:0;return{t1:a.t,t5:b.t,t15:c.t,e1:a.e,e5:b.e,e15:c.e,last1:a.last,prev1:a.prev,last5:b.last,prev5:b.prev,last15:c.last,prev15:c.prev,spike1:avg(v1.slice(-21,-1))?v1.at(-1)/avg(v1.slice(-21,-1)):0,spike5:avg(v5.slice(-11,-1))?v5.at(-1)/avg(v5.slice(-11,-1)):0,high1:num(k1.at(-1)?.[2]),low1:num(k1.at(-1)?.[3]),high5:num(k5.at(-1)?.[2]),low5:num(k5.at(-1)?.[3]),high15:num(k15.at(-1)?.[2]),low15:num(k15.at(-1)?.[3]),atr1:atr(k1),atr5:atr(k5)}}
function signal(d,cfg,engine,r){const entry=engine==='scalp'?d.t1:d.t5,confirm=engine==='scalp'?d.t5:d.t15,spike=engine==='scalp'?d.spike1:d.spike5,last=engine==='scalp'?d.last1:d.last5,prev=engine==='scalp'?d.prev1:d.prev5,ema=engine==='scalp'?d.e1:d.e5,chg=r.change,changeScore=Math.min(Math.abs(chg)/(cfg.minChange*4),1)*30,spikeScore=Math.min(Math.max(spike-cfg.minSpike,0)/2,1)*25,volumeScore=Math.min(r.volume/5e7,1)*20,trendScore=entry===confirm&&entry!=='WAIT'?25:0,score=Math.round(changeScore+spikeScore+volumeScore+trendScore),buy=chg>=cfg.minChange&&score>=cfg.minScore&&spike>=cfg.minSpike&&entry==='BULLISH'&&confirm==='BULLISH'&&last>prev&&last>ema,sell=chg<=-cfg.minChange&&score>=cfg.minScore&&spike>=cfg.minSpike&&entry==='BEARISH'&&confirm==='BEARISH'&&last<prev&&last<ema,s=buy?'BUY':sell?'SELL':'WATCH';return{signal:s,score,spike,entry,confirm,reason:s==='BUY'?`24H +${chg.toFixed(2)}% · Volume ${spike.toFixed(1)}x · ${entry}+${confirm} bullish`:s==='SELL'?`24H ${chg.toFixed(2)}% · Volume ${spike.toFixed(1)}x · ${entry}+${confirm} bearish`:entry==='WAIT'||confirm==='WAIT'?`Waiting for ${cfg.entry}/${cfg.confirm} confirmation`:spike<cfg.minSpike?`Volume spike ${spike.toFixed(1)}x below ${cfg.minSpike}x`:score<cfg.minScore?`Score ${score} below ${cfg.minScore}`:'Trend/24H conditions not fully aligned'}}
function loadStore(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
function App(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[analysis,setAnalysis]=useState(false),[err,setErr]=useState(''),[paper,setPaper]=useState(()=>localStorage.getItem('deal-paper')==='1'),[capital,setCapital]=useState(()=>num(localStorage.getItem('deal-capital'))||START),[baseCapital,setBaseCapital]=useState(()=>num(localStorage.getItem('deal-base-capital'))||START),[risk,setRisk]=useState(()=>Math.min(2,Math.max(.25,num(localStorage.getItem('deal-risk'))||1))),[mp,setMp]=useState(()=>loadStore('deal-momentum-pos',[])),[sp,setSp]=useState(()=>loadStore('deal-scalp-pos',[])),[mt,setMt]=useState(()=>loadStore('deal-momentum-trades',[])),[st,setSt]=useState(()=>loadStore('deal-scalp-trades',[])),[search,setSearch]=useState(''),[side,setSide]=useState('ALL'),[sort,setSort]=useState('fixed'),[minVol,setMinVol]=useState(100000),[lastUpdate,setLastUpdate]=useState('—');
 const orderRef=useRef(loadStore('deal-coin-order',[])),busy=useRef(false),seen=useRef({momentum:new Map,scalp:new Map});
 useEffect(()=>localStorage.setItem('deal-paper',paper?'1':'0'),[paper]);useEffect(()=>localStorage.setItem('deal-capital',capital),[capital]);useEffect(()=>localStorage.setItem('deal-base-capital',baseCapital),[baseCapital]);useEffect(()=>localStorage.setItem('deal-risk',risk),[risk]);useEffect(()=>localStorage.setItem('deal-momentum-pos',JSON.stringify(mp)),[mp]);useEffect(()=>localStorage.setItem('deal-scalp-pos',JSON.stringify(sp)),[sp]);useEffect(()=>localStorage.setItem('deal-momentum-trades',JSON.stringify(mt)),[mt]);useEffect(()=>localStorage.setItem('deal-scalp-trades',JSON.stringify(st)),[st]);
 async function load(){if(busy.current)return;busy.current=true;setAnalysis(true);try{const j=await getJSON(TICKER),all=j.filter(x=>x.symbol?.endsWith('USDT')&&!['USDCUSDT','BTCDOMUSDT'].includes(x.symbol));const map=new Map(all.map(x=>[x.symbol,x]));let order=orderRef.current.filter(s=>map.has(s));if(!order.length){order=all.slice().sort((a,b)=>Math.abs(num(b.priceChangePercent))-Math.abs(num(a.priceChangePercent))).slice(0,50).map(x=>x.symbol);orderRef.current=order;localStorage.setItem('deal-coin-order',JSON.stringify(order))}else if(order.length<50){for(const x of all.slice().sort((a,b)=>Math.abs(num(b.priceChangePercent))-Math.abs(num(a.priceChangePercent))))if(!order.includes(x.symbol)&&order.length<50)order.push(x.symbol);orderRef.current=order;localStorage.setItem('deal-coin-order',JSON.stringify(order))}const base=order.map(symbol=>{const x=map.get(symbol);return x?{symbol,change:num(x.priceChangePercent),volume:num(x.quoteVolume),lastPrice:num(x.lastPrice),high:num(x.highPrice),low:num(x.lowPrice),momentum:{signal:'WATCH',score:0,spike:0,entry:'WAIT',confirm:'WAIT',reason:'Candle analysis pending'},scalp:{signal:'WATCH',score:0,spike:0,entry:'WAIT',confirm:'WAIT',reason:'Candle analysis pending'}}:null}).filter(Boolean);if(!base.length)throw Error('No Binance USDT perpetual coins returned');setRows(prev=>base.map(r=>{const o=prev.find(x=>x.symbol===r.symbol);return o?{...o,change:r.change,volume:r.volume,lastPrice:r.lastPrice,high:r.high,low:r.low}:r}));setLoading(false);setErr('');setLastUpdate(new Date().toLocaleTimeString());for(let i=0;i<base.length;i+=5){const batch=base.slice(i,i+5),done=await Promise.all(batch.map(async r=>{try{const[k1,k5,k15]=await Promise.all([candles(r.symbol,'1m',25),candles(r.symbol,'5m',25),candles(r.symbol,'15m',20)]),d=enrich(k1,k5,k15);return{symbol:r.symbol,d,momentum:signal(d,CFG.momentum,'momentum',r),scalp:signal(d,CFG.scalp,'scalp',r)}}catch{return null}}));setRows(prev=>prev.map(r=>{const x=done.find(q=>q?.symbol===r.symbol);return x?{...r,...x.d,momentum:x.momentum,scalp:x.scalp}:r}))}}catch(e){setErr(e.message||'Market data error');if(!rows.length)setLoading(false)}finally{busy.current=false;setAnalysis(false)}}
 useEffect(()=>{load();const id=setInterval(load,REFRESH);return()=>clearInterval(id)},[]);
 const filtered=useMemo(()=>{let a=rows.filter(r=>r.volume>=minVol&&(!search||r.symbol.toLowerCase().includes(search.toLowerCase())));if(side!=='ALL')a=a.filter(r=>r.momentum.signal===side||r.scalp.signal===side);if(sort==='score')a.sort((x,y)=>Math.max(y.momentum.score,y.scalp.score)-Math.max(x.momentum.score,x.scalp.score));else if(sort==='change')a.sort((x,y)=>Math.abs(y.change)-Math.abs(x.change));else if(sort==='volume')a.sort((x,y)=>y.volume-x.volume);return a},[rows,minVol,search,side,sort]);
 const buys=rows.filter(r=>r.momentum.signal==='BUY'||r.scalp.signal==='BUY').length,sells=rows.filter(r=>r.momentum.signal==='SELL'||r.scalp.signal==='SELL').length,topPump=rows.length?rows.reduce((b,r)=>r.change>b.change?r:b,rows[0]):null;
 const stats=(p,t)=>{const unreal=p.reduce((s,x)=>s+num(x.pnl),0),real=t.reduce((s,x)=>s+num(x.pnl),0),wins=t.filter(x=>num(x.pnl)>0).length;return{unreal,real,total:real+unreal,closed:t.length,open:p.length,wr:t.length?wins/t.length*100:0}};
 const ms=stats(mp,mt),ss=stats(sp,st),combined=ms.total+ss.total;
 function updatePositions(list,setList,setTrades,engine){const closed=[];const next=list.map(p=>{const r=rows.find(x=>x.symbol===p.symbol);if(!r)return p;const px=num(r.lastPrice);if(px<=0)return p;const cfg=CFG[engine],long=p.side==='LONG',high=engine==='scalp'?num(r.high1):num(r.high5),low=engine==='scalp'?num(r.low1):num(r.low5);const riskUnit=Math.abs(num(p.entry)-num(p.initialSL));if(!riskUnit)return p;let stage=num(p.stage),sl=num(p.sl),highest=num(p.highest)||p.entry,lowest=num(p.lowest)||p.entry,tp1=num(p.tp1)|| (long?p.entry+riskUnit:p.entry-riskUnit),finalTp=num(p.finalTp)||(long?p.entry+2*riskUnit:p.entry-2*riskUnit);const finalHit=long?(px>=finalTp||high>=finalTp):(px<=finalTp||low<=finalTp);if(finalHit){const exit=finalTp,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'FINAL TP',execution:'Final 2R'});return null}if(stage<1){const hitSL=long?(px<=sl||low<=sl):(px>=sl||high>=sl),hitTP1=long?(px>=tp1||high>=tp1):(px<=tp1||low<=tp1);if(hitSL){const exit=sl,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'SL',execution:'Initial SL'});return null}if(hitTP1){stage=1;sl=long?p.entry+riskUnit*cfg.lockR:p.entry-riskUnit*cfg.lockR;highest=px;lowest=px;return{...p,current:px,pnl:0,stage,sl,tp1,finalTp,status:'TP1 HIT · PROFIT LOCK',highest,lowest,trailDist:0}}}highest=long?Math.max(highest,px):highest;lowest=!long?Math.min(lowest,px):lowest;const av=engine==='scalp'?num(r.atr1):num(r.atr5),dist=Math.min(Math.max(av*cfg.trailMult,riskUnit*cfg.trailMin),riskUnit*cfg.trailMax);sl=long?Math.max(sl,p.entry+riskUnit*cfg.lockR,highest-dist):Math.min(sl,p.entry-riskUnit*cfg.lockR,lowest+dist);const trailHit=long?(px<=sl||low<=sl):(px>=sl||high>=sl);if(trailHit){const exit=sl,pnl=(long?exit-p.entry:p.entry-exit)*p.qty;closed.push({...p,exit,pnl,closedAt:new Date().toISOString(),exitReason:'LOCK/ATR TRAIL',execution:'Trailing SL after TP1'});return null}return{...p,current:px,pnl:(long?px-p.entry:p.entry-px)*p.qty,stage,sl,tp1,finalTp,status:'TRAILING',highest,lowest,trailDist:dist}}).filter(Boolean);if(closed.length){const realised=closed.reduce((s,x)=>s+num(x.pnl),0);setTrades(t=>[...closed,...t].slice(0,100));setCapital(c=>Math.max(0,c+realised))}setList(next)}
 useEffect(()=>{if(paper){updatePositions(mp,setMp,setMt,'momentum');updatePositions(sp,setSp,setSt,'scalp')}},[rows,paper]);
 function autoOpen(engine,list,setList){if(!paper||list.length>=5)return;const cfg=CFG[engine];rows.filter(r=>r[engine].signal==='BUY'||r[engine].signal==='SELL').forEach(r=>{const s=r[engine],key=keyFor(engine,r.symbol)+':'+s.signal,now=Date.now(),last=seen.current[engine].get(key)||0;if(now-last<cfg.cool)return;setList(p=>{if(p.length>=5||p.some(x=>x.symbol===r.symbol))return p;const entry=num(r.lastPrice);if(entry<=0)return p;const sl=s.signal==='BUY'?entry*(1-cfg.sl):entry*(1+cfg.sl),riskUnit=Math.abs(entry-sl),tp1=s.signal==='BUY'?entry+riskUnit:entry-riskUnit,finalTp=s.signal==='BUY'?entry+2*riskUnit:entry-2*riskUnit,qty=(capital*risk/100)/riskUnit;seen.current[engine].set(key,now);return[...p,{symbol:r.symbol,engine,side:s.signal==='BUY'?'LONG':'SHORT',entry,qty,initialSL:sl,risk:riskUnit,sl,tp1,finalTp,current:entry,pnl:0,stage:0,highest:entry,lowest:entry,openedAt:new Date().toISOString(),signalScore:s.score,signalReason:s.reason,status:'INITIAL SL'}]})})}
 useEffect(()=>{autoOpen('momentum',mp,setMp);autoOpen('scalp',sp,setSp)},[rows,paper,capital,risk,mt.length,st.length]);
 function resetAll(){if(!confirm('Reset both paper engines, positions, history and virtual equity?'))return;setCapital(baseCapital);setMp([]);setSp([]);setMt([]);setSt([]);seen.current={momentum:new Map,scalp:new Map}}
 function posBlock(title,list){return <div className="positions"><h3>{title}</h3>{list.length?<div className="position-list">{list.map((p,i)=><div className="position" key={p.symbol+'-'+i}><b>{p.symbol}</b><span className={p.side==='LONG'?'up':'down'}>{p.side}</span><span>Entry {fmt(p.entry)}</span><span>Now {fmt(p.current)}</span><span>SL {fmt(p.sl)}</span><span>TP1 {fmt(p.tp1)}</span><span>2R {fmt(p.finalTp)}</span><span>P&L {p.pnl>=0?'+':''}{p.pnl.toFixed(2)}</span><span>{p.status}</span></div>)}</div>:<div className="empty">No open paper positions.</div>}</div>}
 function tradeBlock(title,list){return <div className="trades"><h3>{title}</h3>{list.length?list.slice(0,20).map((t,i)=><div key={i}><b>{t.symbol}</b> · {t.side} · Entry {fmt(t.entry)} → Exit {fmt(t.exit)} · <span className={num(t.pnl)>=0?'up':'down'}>{num(t.pnl)>=0?'+':''}{num(t.pnl).toFixed(2)}</span> · {t.exitReason} · {new Date(t.closedAt).toLocaleTimeString()}</div>):<div>No closed paper trades yet.</div>}</div>}
 const recent=useMemo(()=>[...mp.map(x=>({...x,type:'MOMENTUM'})),...sp.map(x=>({...x,type:'SCALPING'}))].sort((a,b)=>new Date(b.openedAt)-new Date(a.openedAt)),[mp,sp]);
 const allClosed=useMemo(()=>[...mt.map(x=>({...x,type:'MOMENTUM'})),...st.map(x=>({...x,type:'SCALPING'}))].sort((a,b)=>new Date(b.closedAt)-new Date(a.closedAt)),[mt,st]);
 return <div className="app"><header><div><div className="brand">⚡ BINANCE SCANNER</div><div className="sub">Binance USDⓈ-M Futures · Live Momentum + Scalping Scanner</div></div><div className="live"><span/>LIVE · 15s</div></header>
 <section className="hero"><div><h1>Momentum + Scalping Scanner</h1><p>Full Delta-style dual-engine scanner on Binance Futures. Top 50 coins are selected once when the scanner starts; coin identity and row order stay stable while price, volume and signals update live. Paper trading only — real orders remain OFF.</p></div><button onClick={load} disabled={analysis}>↻ Refresh</button></section>
 <section className="cards"><div className="card"><small>COMBINED EQUITY</small><strong>{fmt(capital+combined)}</strong><span>Realised {combined.toFixed(2)} · Unrealised {(ms.unreal+ss.unreal).toFixed(2)}</span></div><div className="card"><small>MOMENTUM ENGINE</small><strong>{ms.wr.toFixed(1)}%</strong><span>Win rate · {ms.closed} closed · {ms.open} open · P&L {ms.total.toFixed(2)}</span></div><div className="card"><small>SCALPING ENGINE</small><strong>{ss.wr.toFixed(1)}%</strong><span>Win rate · {ss.closed} closed · {ss.open} open · P&L {ss.total.toFixed(2)}</span></div><div className="card"><small>MARKET SNAPSHOT</small><strong className="up">{topPump?`${topPump.change>=0?'+':''}${topPump.change.toFixed(2)}%`:'—'}</strong><span>{topPump?.symbol||'Waiting'} · BUY {buys} · SELL {sells}</span></div></section>
 <section className="panel paper"><div className="panelhead"><h2>📄 DUAL PAPER TRADING ACCOUNT</h2><span>NO REAL ORDERS</span></div><div className="papergrid"><div className="dualbox"><b>Paper Trading {paper?'ON':'OFF'}</b><span>Virtual capital only. Binance public market data is used; API keys and real order execution are not used.</span><button className="toggle" onClick={()=>setPaper(v=>!v)}>{paper?'Turn OFF':'Turn ON'}</button></div><label>VIRTUAL CAPITAL<input type="number" value={baseCapital} onChange={e=>{const v=Math.max(0,num(e.target.value));setBaseCapital(v);if(!paper)setCapital(v)}}/></label><label>RISK / TRADE %<input type="number" min=".25" max="2" step=".25" value={risk} onChange={e=>setRisk(Math.min(2,Math.max(.25,num(e.target.value))))}/></label><button onClick={resetAll}>Reset Both</button></div><p className="papernote">{paper?'Paper trading is ON. Simulated entries can be created from both Momentum and Scalping signals.':'Paper trading is OFF. Scanner continues to show live Binance market signals.'}</p></section>
 <section className="panel"><div className="panelhead"><h2>V4 ADAPTIVE EXIT EXECUTION</h2><span>SL → TP1 → PROFIT LOCK → ATR TRAIL → FINAL 2R</span></div><div className="analytics-grid"><div><b>Momentum</b><span>Entry 5m + Confirm 15m · SL 1% · Min score 75 · Spike 2x · Lock 0.25R · ATR trail</span></div><div><b>Scalping</b><span>Entry 1m + Confirm 5m · SL 0.5% · Min score 80 · Spike 2x · Lock 0.20R · ATR trail</span></div><div><b>Continuous opportunity</b><span>Cooldown prevents duplicate entries while allowing new signals after the engine cooldown.</span></div></div></section>
 {err&&<div className="error">⚠ {err} <button onClick={load}>Retry</button></div>}
 <div className="controls"><input placeholder="Search coin…" value={search} onChange={e=>setSearch(e.target.value)}/><label>MIN VOLUME <input value={minVol} onChange={e=>setMinVol(Math.max(0,num(e.target.value)))}/></label><label>SIGNAL <select value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option><option>WATCH</option></select></label><label>SORT <select value={sort} onChange={e=>setSort(e.target.value)}><option value="fixed">Fixed Coin Order</option><option value="score">Best Score</option><option value="change">24H Change</option><option value="volume">Volume</option></select></label><span className="updated">Updated {lastUpdate}{analysis?' · analysing…':''}</span></div>
 <section className="panel"><div className="panelhead"><h2>Market Scanner — Both Engines</h2><span>{loading?'Loading Binance coins…':`${filtered.length} coins shown · stable list`}</span></div><div className="tablewrap"><table><thead><tr><th>COIN</th><th>PRICE</th><th>24H</th><th>VOLUME</th><th>MOMENTUM 5M</th><th>15M</th><th>M-SCORE</th><th>SCALP 1M</th><th>5M</th><th>S-SCORE</th><th>SIGNAL</th></tr></thead><tbody>{loading&&!rows.length?<tr><td colSpan="11" className="empty">Loading live Binance Futures coins…</td></tr>:filtered.length?filtered.map(r=>{const sig=r.momentum.signal!=='WATCH'?r.momentum:r.scalp;return <tr key={r.symbol} className={sig.signal==='BUY'?'signal-buy':sig.signal==='SELL'?'signal-sell':'signal-watch'}><td className="symbol">{r.symbol}</td><td>{fmt(r.lastPrice)}</td><td className={r.change>=0?'change-positive':'change-negative'}>{r.change>=0?'+':''}{r.change.toFixed(2)}%</td><td>{money(r.volume)}</td><td className={r.t5==='BULLISH'?'trend-bullish':r.t5==='BEARISH'?'trend-bearish':'trend-wait'}>{r.t5}</td><td className={r.t15==='BULLISH'?'trend-bullish':r.t15==='BEARISH'?'trend-bearish':'trend-wait'}>{r.t15}</td><td>{r.momentum.score}</td><td className={r.t1==='BULLISH'?'trend-bullish':r.t1==='BEARISH'?'trend-bearish':'trend-wait'}>{r.t1}</td><td className={r.t5==='BULLISH'?'trend-bullish':r.t5==='BEARISH'?'trend-bearish':'trend-wait'}>{r.t5}</td><td>{r.scalp.score}</td><td><span className={'pill '+sig.signal.toLowerCase()}>{sig.signal}</span></td></tr>}) : <tr><td colSpan="11" className="empty">No coins match the current filter.</td></tr>}</tbody></table></div></section>
 <section className="panel history"><div className="panelhead"><h2>Paper Trading Analytics</h2><span>{allClosed.length} closed trades · {recent.length} open positions</span></div><div className="analytics-grid stats"><div><b>Momentum</b><span>Win {ms.wr.toFixed(1)}% · Realised {ms.real.toFixed(2)} · Unrealised {ms.unreal.toFixed(2)}</span></div><div><b>Scalping</b><span>Win {ss.wr.toFixed(1)}% · Realised {ss.real.toFixed(2)} · Unrealised {ss.unreal.toFixed(2)}</span></div><div><b>Combined</b><span>Net paper P&L {(ms.total+ss.total).toFixed(2)} · Equity {(capital+combined).toFixed(2)}</span></div></div></section>
 <section className="panel history"><div className="panelhead"><h2>Scanner Execution Settings</h2><span>Binance public data · no API keys</span></div><div className="analytics-grid"><div><b>Stable universe</b><span>Top 50 selected once and persisted locally. Live refresh updates market values without replacing the coin list.</span></div><div><b>Momentum</b><span>5m entry + 15m confirmation · 1% SL · 2R final target · 9 minute cooldown · max 5 open positions.</span></div><div><b>Scalping</b><span>1m entry + 5m confirmation · 0.5% SL · 2R final target · 3 minute cooldown · max 5 open positions.</span></div></div></section>
 <section className="panel history"><div className="panelhead"><h2>Recent Paper Entry Log</h2><span>Latest simulated entries</span></div><div className="trades">{recent.length?recent.slice(0,20).map((p,i)=><div key={i}><b>{p.type}</b> · {p.symbol} · {p.side} · Entry {fmt(p.entry)} · Score {p.signalScore} · {new Date(p.openedAt).toLocaleTimeString()} · {p.signalReason}</div>):<div>No paper entries yet.</div>}</div></section>
 <section className="panel history">{posBlock('Momentum Positions & History',mp)}{tradeBlock('Momentum Closed History',mt)}</section><section className="panel history">{posBlock('Scalping Positions & History',sp)}{tradeBlock('Scalping Closed History',st)}</section>
 <footer>Binance USDⓈ-M Futures public market data · Dual Momentum + Scalping engines · Paper trading only · Stable top-50 coin list · Live refresh every 15 seconds · Real orders OFF</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
