import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const TICKER='https://fapi.binance.com/fapi/v1/ticker/24hr',KLINES='https://fapi.binance.com/fapi/v1/klines';
const REFRESH=15000,START=10000;
const CFG={momentum:{entry:'5m',confirm:'15m',sl:.01,tp:2,minSpike:2,minScore:75,minChange:2,cool:900000,lockR:.25,trailMult:1.5,trailMin:.5,trailMax:1.2,max:5},scalp:{entry:'1m',confirm:'5m',sl:.005,tp:2,minSpike:2,minScore:80,minChange:.5,cool:300000,lockR:.2,trailMult:1,trailMin:.5,trailMax:1,max:5}};
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=v=>n(v).toLocaleString('en-US',{maximumFractionDigits:8});
const money=v=>{const x=Math.abs(n(v));return(x>=1e9?'$'+(x/1e9).toFixed(2)+'B':x>=1e6?'$'+(x/1e6).toFixed(2)+'M':x>=1e3?'$'+(x/1e3).toFixed(1)+'K':'$'+x.toFixed(0))};
const store=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
async function json(url,opts){const r=await fetch(url,{cache:'no-store',...opts});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={}}if(!r.ok)throw Error(j.msg||j.error||`HTTP ${r.status}`);return j}
async function kl(symbol,interval,limit=30){return json(`${KLINES}?symbol=${symbol}&interval=${interval}&limit=${limit}`)}
function atr(k,p=14){if(k.length<p+1)return 0;let s=0;for(let i=k.length-p;i<k.length;i++){const h=n(k[i][2]),l=n(k[i][3]),pc=n(k[i-1][4]);s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/p}
function trend(k){const c=k.map(x=>n(x[4])).filter(Boolean);if(c.length<6)return{t:'WAIT',e:0,last:0,prev:0};const a=2/9;let e=c[0];for(let i=1;i<c.length;i++)e=c[i]*a+e*(1-a);const last=c.at(-1),prev=c.at(-2);return{t:last>prev&&last>e?'BULLISH':last<prev&&last<e?'BEARISH':'WAIT',e,last,prev}}
function enrich(k1,k5,k15){const a=trend(k1),b=trend(k5),c=trend(k15),avg=x=>x.length?x.reduce((s,v)=>s+v,0)/x.length:0,v1=k1.map(x=>n(x[5])),v5=k5.map(x=>n(x[5]));return{t1:a.t,t5:b.t,t15:c.t,e1:a.e,e5:b.e,e15:c.e,last1:a.last,prev1:a.prev,last5:b.last,prev5:b.prev,last15:c.last,prev15:c.prev,spike1:avg(v1.slice(-21,-1))?v1.at(-1)/avg(v1.slice(-21,-1)):0,spike5:avg(v5.slice(-11,-1))?v5.at(-1)/avg(v5.slice(-11,-1)):0,high1:n(k1.at(-1)?.[2]),low1:n(k1.at(-1)?.[3]),high5:n(k5.at(-1)?.[2]),low5:n(k5.at(-1)?.[3]),high15:n(k15.at(-1)?.[2]),low15:n(k15.at(-1)?.[3]),atr1:atr(k1),atr5:atr(k5)}}
function signal(d,cfg,engine,r){const entry=engine==='scalp'?d.t1:d.t5,confirm=engine==='scalp'?d.t5:d.t15,spike=engine==='scalp'?d.spike1:d.spike5,last=engine==='scalp'?d.last1:d.last5,prev=engine==='scalp'?d.prev1:d.prev5,ema=engine==='scalp'?d.e1:d.e5;const changeScore=Math.min(Math.abs(r.change)/(cfg.minChange*4),1)*30,spikeScore=Math.min(Math.max(spike-cfg.minSpike,0)/2,1)*25,volumeScore=Math.min(r.volume/5e7,1)*20,trendScore=entry===confirm&&entry!=='WAIT'?25:0,score=Math.round(changeScore+spikeScore+volumeScore+trendScore),buy=r.change>=cfg.minChange&&score>=cfg.minScore&&spike>=cfg.minSpike&&entry==='BULLISH'&&confirm==='BULLISH'&&last>prev&&last>ema,sell=r.change<=-cfg.minChange&&score>=cfg.minScore&&spike>=cfg.minSpike&&entry==='BEARISH'&&confirm==='BEARISH'&&last<prev&&last<ema;return{signal:buy?'BUY':sell?'SELL':'WATCH',score,spike,entry,confirm,reason:buy?`24H +${r.change.toFixed(2)}% · ${spike.toFixed(1)}x volume · bullish confirmation`:sell?`24H ${r.change.toFixed(2)}% · ${spike.toFixed(1)}x volume · bearish confirmation`:`${entry}/${confirm} confirmation pending`}}
function App(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[analysing,setAnalysing]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState(()=>localStorage.getItem('deal-mode')||'paper'),[capital,setCapital]=useState(()=>n(localStorage.getItem('deal-capital'))||START),[baseCapital,setBaseCapital]=useState(()=>n(localStorage.getItem('deal-base-capital'))||START),[risk,setRisk]=useState(()=>Math.min(2,Math.max(.25,n(localStorage.getItem('deal-risk'))||1))),[mp,setMp]=useState(()=>store('deal-momentum-pos',[])),[sp,setSp]=useState(()=>store('deal-scalp-pos',[])),[mt,setMt]=useState(()=>store('deal-momentum-trades',[])),[st,setSt]=useState(()=>store('deal-scalp-trades',[])),[search,setSearch]=useState(''),[side,setSide]=useState('ALL'),[sort,setSort]=useState('fixed'),[minVol,setMinVol]=useState(100000),[lastUpdate,setLastUpdate]=useState('—'),[liveBusy,setLiveBusy]=useState(false),[liveMsg,setLiveMsg]=useState('');
 const order=useRef(store('deal-coin-order',[])), busy=useRef(false), fired=useRef(new Map()), liveClose=useRef(new Set());
 useEffect(()=>localStorage.setItem('deal-mode',mode),[mode]);useEffect(()=>localStorage.setItem('deal-capital',capital),[capital]);useEffect(()=>localStorage.setItem('deal-base-capital',baseCapital),[baseCapital]);useEffect(()=>localStorage.setItem('deal-risk',risk),[risk]);useEffect(()=>localStorage.setItem('deal-momentum-pos',JSON.stringify(mp)),[mp]);useEffect(()=>localStorage.setItem('deal-scalp-pos',JSON.stringify(sp)),[sp]);useEffect(()=>localStorage.setItem('deal-momentum-trades',JSON.stringify(mt)),[mt]);useEffect(()=>localStorage.setItem('deal-scalp-trades',JSON.stringify(st)),[st]);
 async function load(){if(busy.current)return;busy.current=true;setAnalysing(true);try{const all=(await json(TICKER)).filter(x=>x.symbol?.endsWith('USDT')&&!['USDCUSDT','BTCDOMUSDT'].includes(x.symbol));const map=new Map(all.map(x=>[x.symbol,x]));let list=order.current.filter(s=>map.has(s));if(!list.length)list=all.slice().sort((a,b)=>Math.abs(n(b.priceChangePercent))-Math.abs(n(a.priceChangePercent))).slice(0,50).map(x=>x.symbol);for(const x of all.slice().sort((a,b)=>Math.abs(n(b.priceChangePercent))-Math.abs(n(a.priceChangePercent))))if(list.length<50&&!list.includes(x.symbol))list.push(x.symbol);order.current=list.slice(0,50);localStorage.setItem('deal-coin-order',JSON.stringify(order.current));const base=order.current.map(symbol=>{const x=map.get(symbol);return x?{symbol,change:n(x.priceChangePercent),volume:n(x.quoteVolume),lastPrice:n(x.lastPrice),high:n(x.highPrice),low:n(x.lowPrice)}:null}).filter(Boolean);setRows(prev=>base.map(r=>{const old=prev.find(x=>x.symbol===r.symbol);return old?{...old,...r,momentum:old.momentum,scalp:old.scalp}:r}));setLoading(false);setError('');setLastUpdate(new Date().toLocaleTimeString());for(let i=0;i<base.length;i+=5){const batch=base.slice(i,i+5),done=await Promise.all(batch.map(async r=>{try{const[a,b,c]=await Promise.all([kl(r.symbol,'1m',25),kl(r.symbol,'5m',25),kl(r.symbol,'15m',20)]);const d=enrich(a,b,c);return{symbol:r.symbol,...d,momentum:signal(d,CFG.momentum,'momentum',r),scalp:signal(d,CFG.scalp,'scalp',r)}}catch{return null}}));setRows(prev=>prev.map(r=>{const q=done.find(x=>x?.symbol===r.symbol);return q?{...r,...q}:r}))}}catch(e){setError(e.message||'Binance market data error');if(!rows.length)setLoading(false)}finally{busy.current=false;setAnalysing(false)}}
 useEffect(()=>{load();const id=setInterval(load,REFRESH);return()=>clearInterval(id)},[]);
 const filtered=useMemo(()=>{let a=rows.filter(r=>r.volume>=minVol&&(!search||r.symbol.toLowerCase().includes(search.toLowerCase())));if(side!=='ALL')a=a.filter(r=>r.momentum?.signal===side||r.scalp?.signal===side);if(sort==='score')a.sort((x,y)=>Math.max(y.momentum?.score||0,y.scalp?.score||0)-Math.max(x.momentum?.score||0,x.scalp?.score||0));else if(sort==='change')a.sort((x,y)=>Math.abs(y.change)-Math.abs(x.change));else if(sort==='volume')a.sort((x,y)=>y.volume-x.volume);return a},[rows,minVol,search,side,sort]);
 const stats=(p,t)=>{const unreal=p.reduce((s,x)=>s+n(x.pnl),0),real=t.reduce((s,x)=>s+n(x.pnl),0),wins=t.filter(x=>n(x.pnl)>0).length;return{unreal,real,total:real+unreal,closed:t.length,open:p.length,wr:t.length?wins/t.length*100:0}};const ms=stats(mp,mt),ss=stats(sp,st),combined=ms.total+ss.total;const buys=rows.filter(r=>r.momentum?.signal==='BUY'||r.scalp?.signal==='BUY').length,sells=rows.filter(r=>r.momentum?.signal==='SELL'||r.scalp?.signal==='SELL').length,top=rows.length?rows.reduce((a,b)=>b.change>a.change?b:a,rows[0]):null;
 async function liveOrder(p,close=false){if(mode!=='live')return true;setLiveBusy(true);try{const res=await json('/api/binance-trade.js',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'order',symbol:p.symbol,side:close?(p.side==='LONG'?'SELL':'BUY'):(p.side==='LONG'?'BUY':'SELL'),quantity:p.qty,reduceOnly:close})});if(!res.ok)throw Error(res.error||'Live order failed');setLiveMsg(`${close?'Closed':'Opened'} ${p.symbol} ${p.side}`);return true}catch(e){setLiveMsg(e.message);return false}finally{setLiveBusy(false)}}
 function open(engine,r){const cfg=CFG[engine],sig=r[engine];if(!sig||sig.signal==='WATCH')return;if((mp.some(x=>x.symbol===r.symbol)&&engine==='momentum')||(sp.some(x=>x.symbol===r.symbol)&&engine==='scalp'))return;const entry=n(r.lastPrice);if(!entry)return;const sl=sig.signal==='BUY'?entry*(1-cfg.sl):entry*(1+cfg.sl),unit=Math.abs(entry-sl),qty=Math.max(0,(capital*risk/100)/unit);const p={symbol:r.symbol,engine,side:sig.signal==='BUY'?'LONG':'SHORT',entry,qty,initialSL:sl,risk:unit,sl,tp1:sig.signal==='BUY'?entry+unit:entry-unit,finalTp:sig.signal==='BUY'?entry+2*unit:entry-2*unit,current:entry,pnl:0,stage:0,highest:entry,lowest:entry,openedAt:new Date().toISOString(),signalScore:sig.score,signalReason:sig.reason,status:'INITIAL SL'};const key=engine+r.symbol+sig.signal;if(Date.now()-(fired.current.get(key)||0)<cfg.cool)return;fired.current.set(key,Date.now());(engine==='momentum'?setMp:setSp)(p0=>[...p0,p]);if(mode==='live')liveOrder(p);}
 useEffect(()=>{if(mode!=='off')rows.forEach(r=>{if(r.momentum?.signal==='BUY'||r.momentum?.signal==='SELL')open('momentum',r);if(r.scalp?.signal==='BUY'||r.scalp?.signal==='SELL')open('scalp',r)})},[rows,mode]);
 async function manage(list,setList,setTrades,engine){const cfg=CFG[engine],closed=[];const next=list.map(p=>{const r=rows.find(x=>x.symbol===p.symbol);if(!r)return p;const px=n(r.lastPrice),long=p.side==='LONG',hi=engine==='scalp'?n(r.high1):n(r.high5),lo=engine==='scalp'?n(r.low1):n(r.low5);let stage=p.stage,sl=p.sl,high=Math.max(n(p.highest)||p.entry,px),low=Math.min(n(p.lowest)||p.entry,px);const final=long?px>=p.finalTp||hi>=p.finalTp:px<=p.finalTp||lo<=p.finalTp;if(final){const q={...p,exit:p.finalTp,pnl:(long?p.finalTp-p.entry:p.entry-p.finalTp)*p.qty,closedAt:new Date().toISOString(),exitReason:'FINAL TP',execution:'Final 2R'};closed.push(q);if(mode==='live'&&!liveClose.current.has(p.symbol+'f')){liveClose.current.add(p.symbol+'f');liveOrder(p,true)}return null}if(stage<1){const stop=long?px<=sl||lo<=sl:px>=sl||hi>=sl,hit=long?px>=p.tp1||hi>=p.tp1:px<=p.tp1||lo<=p.tp1;if(stop){const q={...p,exit:sl,pnl:(long?sl-p.entry:p.entry-sl)*p.qty,closedAt:new Date().toISOString(),exitReason:'SL',execution:'Initial SL'};closed.push(q);if(mode==='live'&&!liveClose.current.has(p.symbol+'s')){liveClose.current.add(p.symbol+'s');liveOrder(p,true)}return null}if(hit){stage=1;sl=long?p.entry+p.risk*cfg.lockR:p.entry-p.risk*cfg.lockR}}const av=engine==='scalp'?n(r.atr1):n(r.atr5),dist=Math.min(Math.max(av*cfg.trailMult,p.risk*cfg.trailMin),p.risk*cfg.trailMax);sl=long?Math.max(sl,p.entry+p.risk*cfg.lockR,high-dist):Math.min(sl,p.entry-p.risk*cfg.lockR,low+dist);const trail=long?px<=sl||lo<=sl:px>=sl||hi>=sl;if(trail){const q={...p,exit:sl,pnl:(long?sl-p.entry:p.entry-sl)*p.qty,closedAt:new Date().toISOString(),exitReason:stage?'LOCK/ATR TRAIL':'SL',execution:'Managed exit'};closed.push(q);if(mode==='live'&&!liveClose.current.has(p.symbol+'t')){liveClose.current.add(p.symbol+'t');liveOrder(p,true)}return null}return{...p,current:px,pnl:(long?px-p.entry:p.entry-px)*p.qty,stage,sl,highest:high,lowest:low,status:stage?'TRAILING':'INITIAL SL'}}).filter(Boolean);if(closed.length){setTrades(t=>[...closed,...t].slice(0,100));setCapital(c=>Math.max(0,c+closed.reduce((s,x)=>s+n(x.pnl),0)))}setList(next)}
 useEffect(()=>{if(mode!=='off'){manage(mp,setMp,setMt,'momentum');manage(sp,setSp,setSt,'scalp')}},[rows,mode]);
 function reset(){if(!confirm('Reset both engines, positions, history and virtual capital?'))return;setMp([]);setSp([]);setMt([]);setSt([]);setCapital(baseCapital);setLiveMsg('Paper/live engine state reset');}
 const tableRows=filtered.length?filtered:[];
 const PositionTable=({title,list})=><section className="panel positions"><h3>{title}</h3>{!list.length?<div className="empty">No open positions</div>:<div className="table-wrap"><table><thead><tr><th>Coin</th><th>Side</th><th>Entry</th><th>Current</th><th>SL</th><th>TP1</th><th>Final TP</th><th>P&L</th><th>Status</th></tr></thead><tbody>{list.map((p,i)=><tr key={p.symbol+i}><td>{p.symbol}</td><td>{p.side}</td><td>{fmt(p.entry)}</td><td>{fmt(p.current)}</td><td>{fmt(p.sl)}</td><td>{fmt(p.tp1)}</td><td>{fmt(p.finalTp)}</td><td className={p.pnl>=0?'pos':'neg'}>{p.pnl>=0?'+':''}{p.pnl.toFixed(2)}</td><td>{p.status}</td></tr>)}</tbody></table></div>}</section>;
 const History=({title,list})=><section className="panel trades"><h3>{title}</h3>{!list.length?<div className="empty">No closed trades yet</div>:<div className="table-wrap"><table><thead><tr><th>Coin</th><th>Side</th><th>Entry</th><th>Exit</th><th>P&L</th><th>Reason</th><th>Time</th></tr></thead><tbody>{list.slice(0,20).map((p,i)=><tr key={i}><td>{p.symbol}</td><td>{p.side}</td><td>{fmt(p.entry)}</td><td>{fmt(p.exit)}</td><td className={p.pnl>=0?'pos':'neg'}>{p.pnl>=0?'+':''}{p.pnl.toFixed(2)}</td><td>{p.exitReason}</td><td>{new Date(p.closedAt).toLocaleTimeString()}</td></tr>)}</tbody></table></div>}</section>;
 return <main className="app"><header className="hero"><div><h1>⚡ BINANCE SCANNER</h1><p>Binance USDⓈ-M Futures · Live Momentum + Scalping Scanner</p><span className="live">● LIVE · 15s</span></div><button onClick={load}>↻ Refresh</button></header>
 <div className="notice">Live Binance Futures perpetual scanner. <b>Coin list is stable</b> after startup; price, volume and signals remain live. Trading supports Paper and Live modes. <b>Real orders stay OFF until Live Trading is explicitly selected.</b></div>
 <section className="cards"><div><small>COMBINED EQUITY</small><strong>₹{(baseCapital+combined).toFixed(2)}</strong><span>Realised ₹{(ms.real+ss.real).toFixed(2)} · Unrealised ₹{(ms.unreal+ss.unreal).toFixed(2)}</span></div><div><small>MOMENTUM</small><strong>{ms.wr.toFixed(1)}%</strong><span>{ms.closed} closed · {ms.open} open · P&L ₹{ms.total.toFixed(2)}</span></div><div><small>SCALPING</small><strong>{ss.wr.toFixed(1)}%</strong><span>{ss.closed} closed · {ss.open} open · P&L ₹{ss.total.toFixed(2)}</span></div><div><small>MARKET SIGNALS</small><strong>{buys} BUY</strong><span>{sells} SELL · Top pump {top?top.symbol:'—'} {top?top.change.toFixed(2):'—'}%</span></div></section>
 <section className="panel trading"><div><h2>Dual Trading Account</h2><p>Binance Futures execution engine</p></div><div className="mode-buttons"><button className={mode==='paper'?'active':''} onClick={()=>setMode('paper')}>📄 PAPER TRADING</button><button className={mode==='live'?'danger active':''} onClick={()=>{if(confirm('LIVE TRADING sends real Binance Futures orders. Continue?'))setMode('live')}}>⚡ LIVE TRADING</button><button className={mode==='off'?'active':''} onClick={()=>setMode('off')}>OFF</button></div><div className="risk-box"><label>Virtual/Base Capital <input type="number" value={baseCapital} onChange={e=>setBaseCapital(Math.max(0,n(e.target.value)))}/></label><label>Risk / Trade % <input type="number" min=".25" max="2" step=".25" value={risk} onChange={e=>setRisk(Math.min(2,Math.max(.25,n(e.target.value))))}/></label><button onClick={reset}>Reset Both</button></div><p className="status">{mode==='paper'?'PAPER MODE · Virtual orders only':mode==='live'?'⚠ LIVE MODE · Real Binance orders enabled':'TRADING OFF'} {liveBusy?' · Executing…':''}</p>{liveMsg&&<p className="hint">{liveMsg}</p>}</section>
 <section className="panel"><h2>V4 Adaptive Exit Execution</h2><div className="engine-grid"><div><b>Momentum Engine</b><p>5m entry + 15m confirmation · SL {(CFG.momentum.sl*100).toFixed(1)}% · TP 2R · ATR trail</p></div><div><b>Scalping Engine</b><p>1m entry + 5m confirmation · SL {(CFG.scalp.sl*100).toFixed(1)}% · TP 2R · ATR trail</p></div></div></section>
 <section className="panel controls"><input placeholder="Search coin…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="fixed">Fixed Coin Order</option><option value="score">Best Score</option><option value="change">24H Change</option><option value="volume">Volume</option></select><select value={minVol} onChange={e=>setMinVol(n(e.target.value))}><option value="0">All Volume</option><option value="100000">100K+</option><option value="1000000">1M+</option><option value="10000000">10M+</option></select><span>{analysing?'Analysing candles…':'Updated '+lastUpdate}</span></section>
 <section className="panel scanner"><div className="section-head"><div><h2>Market Scanner — Both Engines</h2><p>{tableRows.length} coins shown · stable coin order · live Binance data</p></div><span>BUY {buys} · SELL {sells}</span></div><div className="table-wrap"><table><thead><tr><th>COIN</th><th>PRICE</th><th>24H</th><th>VOLUME</th><th>5M</th><th>15M</th><th>1M SPIKE</th><th>MOMENTUM</th><th>SCALP</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="10">Loading Binance Futures…</td></tr>:tableRows.map(r=><tr key={r.symbol}><td><b>{r.symbol}</b></td><td>{fmt(r.lastPrice)}</td><td className={r.change>=0?'pos':'neg'}>{r.change>=0?'+':''}{r.change.toFixed(2)}%</td><td>{money(r.volume)}</td><td>{r.t5||'WAIT'}</td><td>{r.t15||'WAIT'}</td><td>{(r.spike1||0).toFixed(1)}x</td><td><b>{r.momentum?.signal}</b> <small>{r.momentum?.score||0}</small></td><td><b>{r.scalp?.signal}</b> <small>{r.scalp?.score||0}</small></td><td>{r.momentum?.signal!=='WATCH'&&<button onClick={()=>open('momentum',r)}>M</button>} {r.scalp?.signal!=='WATCH'&&<button onClick={()=>open('scalp',r)}>S</button>}</td></tr>)}</tbody></table></div>{error&&<div className="error">{error}</div>}</section>
 <section className="panel analytics"><h2>Paper Trading Analytics</h2><div className="analytics-grid"><div><b>Momentum</b><span>Win Rate {ms.wr.toFixed(1)}%</span><span>Closed {ms.closed}</span><span>Open {ms.open}</span><span>P&L ₹{ms.total.toFixed(2)}</span></div><div><b>Scalping</b><span>Win Rate {ss.wr.toFixed(1)}%</span><span>Closed {ss.closed}</span><span>Open {ss.open}</span><span>P&L ₹{ss.total.toFixed(2)}</span></div><div><b>Risk Engine</b><span>Risk {risk}% / trade</span><span>Max Momentum {CFG.momentum.max}</span><span>Max Scalp {CFG.scalp.max}</span><span>Live API {mode==='live'?'ENABLED':'OFF'}</span></div></div></section>
 <PositionTable title="Momentum Positions & History" list={mp}/><History title="Momentum Closed Trades" list={mt}/><PositionTable title="Scalping Positions & History" list={sp}/><History title="Scalping Closed Trades" list={st}/>
 <footer>Binance USDⓈ-M Futures · Momentum + Scalping · Live market data · Paper trading available · <b>Real orders are executed only in LIVE mode using server-side Binance API credentials.</b></footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
