import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const TICKER='https://fapi.binance.com/fapi/v1/ticker/24hr';
const KLINES='https://fapi.binance.com/fapi/v1/klines';
const REFRESH=15000;
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const priceOf=r=>num(r?.lastPrice||r?.price||r?.marketPrice);
const fmt=v=>num(v).toLocaleString('en-US',{maximumFractionDigits:8});
const money=v=>Math.abs(num(v))>=1e6?'$'+(Math.abs(v)/1e6).toFixed(2)+'M':Math.abs(v)>=1e3?'$'+(Math.abs(v)/1e3).toFixed(1)+'K':'$'+Math.abs(v).toFixed(0);

async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('Binance API HTTP '+r.status);return r.json()}
async function candles(symbol,interval='5m',limit=30){const j=await getJSON(`${KLINES}?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=${limit}`);return Array.isArray(j)?j:[]}
function trend(k){if(k.length<6)return'WAIT';const a=k.map(x=>num(x[4]));const last=a.at(-1),prev=a.at(-2),ema=a.slice(-6).reduce((s,x)=>s+x,0)/Math.min(6,a.length);return last>prev&&last>ema?'BULLISH':last<prev&&last<ema?'BEARISH':'WAIT'}
function spike(k){if(k.length<8)return 0;const v=k.slice(-8,-1).map(x=>num(x[5]));const avg=v.reduce((a,b)=>a+b,0)/v.length;return avg?num(k.at(-1)[5])/avg:0}
function analyse(r,k5,k15){const t5=trend(k5),t15=trend(k15),sp=spike(k5),chg=num(r.change),changeScore=Math.min(Math.abs(chg)/8,1)*30,spikeScore=Math.min(Math.max(sp-2,0)/2,1)*25,trendScore=t5===t15&&t5!=='WAIT'?25:0,score=Math.round(changeScore+spikeScore+trendScore+Math.min(num(r.volume)/50000000,1)*20),buy=chg>=2&&t5==='BULLISH'&&t15==='BULLISH'&&sp>=2&&score>=70,sell=chg<=-2&&t5==='BEARISH'&&t15==='BEARISH'&&sp>=2&&score>=70;return{t5,t15,spike:sp,score,signal:buy?'BUY':sell?'SELL':'WATCH'}}

function App(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[analysing,setAnalysing]=useState(false),[err,setErr]=useState(''),[paper,setPaper]=useState(()=>localStorage.getItem('deal-paper')==='1'),[capital,setCapital]=useState(()=>num(localStorage.getItem('deal-capital'))||10000),[search,setSearch]=useState(''),[side,setSide]=useState('ALL'),[sort,setSort]=useState('score'),[lastUpdate,setLastUpdate]=useState('—');
 async function load(){setAnalysing(true);try{const j=await getJSON(TICKER);if(!Array.isArray(j))throw Error('Invalid Binance ticker response');const base=j.filter(x=>x.symbol?.endsWith('USDT')&&x.symbol!=='USDCUSDT'&&x.symbol!=='BTCDOMUSDT').map(x=>({symbol:x.symbol,change:num(x.priceChangePercent),volume:num(x.quoteVolume),lastPrice:num(x.lastPrice),high:num(x.highPrice),low:num(x.lowPrice),signal:{signal:'WATCH',score:0,spike:0,t5:'WAIT',t15:'WAIT'}})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,50);if(!base.length)throw Error('No Binance USDT perpetual coins returned');setRows(base);setLoading(false);setErr('');setLastUpdate(new Date().toLocaleTimeString());const out=[];for(let i=0;i<base.length;i+=5){const batch=base.slice(i,i+5);const done=await Promise.all(batch.map(async r=>{try{const[k5,k15]=await Promise.all([candles(r.symbol,'5m',30),candles(r.symbol,'15m',20)]);return{symbol:r.symbol,signal:analyse(r,k5,k15)}}catch{return{symbol:r.symbol,signal:r.signal}}}));out.push(...done);setRows(prev=>prev.map(r=>{const x=out.find(q=>q.symbol===r.symbol);return x?{...r,signal:x.signal}:r}))}}catch(e){setErr(e.message||'Market data error');if(!rows.length)setLoading(false)}finally{setAnalysing(false)}}
 useEffect(()=>{load();const id=setInterval(load,REFRESH);return()=>clearInterval(id)},[]);
 useEffect(()=>localStorage.setItem('deal-paper',paper?'1':'0'),[paper]);useEffect(()=>localStorage.setItem('deal-capital',capital),[capital]);
 const filtered=useMemo(()=>{let a=rows.filter(r=>!search||r.symbol.toLowerCase().includes(search.toLowerCase()));if(side!=='ALL')a=a.filter(r=>r.signal.signal===side);return[...a].sort((a,b)=>sort==='change'?Math.abs(b.change)-Math.abs(a.change):sort==='volume'?b.volume-a.volume:b.signal.score-a.signal.score)},[rows,search,side,sort]);
 const buys=rows.filter(r=>r.signal.signal==='BUY').length,sells=rows.filter(r=>r.signal.signal==='SELL').length;
 return <div className="app"><header><div><div className="brand">⚡ BINANCE SCANNER</div><div className="sub">Binance USDⓈ-M Futures · Live Momentum + Scalping Scanner</div></div><div className="live"><span/>LIVE · 15s</div></header>
 <section className="hero"><div><h1>Momentum + Scalping Scanner</h1><p>Live Binance Futures perpetual scanner. Top 50 coins by absolute 24H change, live price/volume and candle confirmation. Paper trading only — real orders remain OFF.</p></div><button onClick={load} disabled={analysing}>↻ Refresh</button></section>
 <section className="cards"><div className="card"><small>COINS LOADED</small><strong>{rows.length}</strong><span>Top Binance USDT perpetuals</span></div><div className="card"><small>TOP PUMP</small><strong className="up">{rows[0]?`+${rows[0].change.toFixed(2)}%`:'—'}</strong><span>{rows[0]?.symbol||'Waiting for market data'}</span></div><div className="card"><small>BUY SIGNALS</small><strong className="up">{buys}</strong><span>5m + 15m confirmation</span></div><div className="card"><small>SELL SIGNALS</small><strong className="down">{sells}</strong><span>Paper mode only</span></div></section>
 <section className="panel paper"><div className="panelhead"><h2>📄 PAPER TRADING</h2><span>NO REAL ORDERS</span></div><div className="papergrid"><div className="dualbox"><b>Paper Trading {paper?'ON':'OFF'}</b><span>Virtual capital only. Binance API keys and real order execution are not used.</span><button className="toggle" onClick={()=>setPaper(v=>!v)}>{paper?'Turn OFF':'Turn ON'}</button></div><label>VIRTUAL CAPITAL<input type="number" value={capital} onChange={e=>setCapital(Math.max(0,num(e.target.value)))}/></label></div><p className="papernote">{paper?'Paper trading is ON. Signals can be used for simulated entries only.':'Paper trading is OFF. Scanner continues to show live market signals.'}</p></section>
 {err&&<div className="error">⚠ {err} <button onClick={load}>Retry</button></div>}
 <div className="controls"><input placeholder="Search coin…" value={search} onChange={e=>setSearch(e.target.value)}/><label>SIGNAL <select value={side} onChange={e=>setSide(e.target.value)}><option>ALL</option><option>BUY</option><option>SELL</option><option>WATCH</option></select></label><label>SORT <select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Score</option><option value="change">24H Change</option><option value="volume">Volume</option></select></label><span style={{marginLeft:'auto',color:'#748196',fontSize:10}}>Updated {lastUpdate}{analysing?' · analysing…':''}</span></div>
 <section className="panel"><div className="panelhead"><h2>Market Radar</h2><span>{loading?'Loading Binance coins…':`${filtered.length} coins shown`}</span></div><div className="tablewrap"><table><thead><tr><th>COIN</th><th>PRICE</th><th>24H</th><th>VOLUME</th><th>5M</th><th>15M</th><th>SPIKE</th><th>SCORE</th><th>SIGNAL</th></tr></thead><tbody>{loading&&!rows.length?<tr><td colSpan="9" className="empty">Loading live Binance Futures coins…</td></tr>:filtered.length?filtered.map(r=><tr key={r.symbol} className={r.signal.signal==='BUY'?'signal-buy':r.signal.signal==='SELL'?'signal-sell':'signal-watch'}><td className="symbol">{r.symbol}</td><td>{fmt(r.lastPrice)}</td><td className={r.change>=0?'change-positive':'change-negative'}>{r.change>=0?'+':''}{r.change.toFixed(2)}%</td><td>{money(r.volume)}</td><td className={r.signal.t5==='BULLISH'?'trend-bullish':r.signal.t5==='BEARISH'?'trend-bearish':'trend-wait'}>{r.signal.t5}</td><td className={r.signal.t15==='BULLISH'?'trend-bullish':r.signal.t15==='BEARISH'?'trend-bearish':'trend-wait'}>{r.signal.t15}</td><td className={r.signal.spike>=2?'hot':''}>{r.signal.spike.toFixed(1)}x</td><td><div className="score"><i style={{width:`${Math.min(r.signal.score,100)}%`}}/><span>{r.signal.score}</span></div></td><td><span className={'pill '+r.signal.signal.toLowerCase()}>{r.signal.signal}</span></td></tr>):<tr><td colSpan="9" className="empty">No coins match the current filter.</td></tr>}</tbody></table></div></section><footer>Binance Futures public market data · Paper trading only · Last refresh every 15 seconds · Real orders OFF</footer></div>}

createRoot(document.getElementById('root')).render(<App/>);
