const KEY='paper-engine-state-v1';
const WS='wss://fstream.binance.com/stream';
let socket=null,retry=null,prices=new Map(),signature='';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function connect(){clearTimeout(retry);const s=read(),symbols=Object.keys(s.positions||{}).filter(Boolean);const sig=symbols.join(',');if(!symbols.length){signature='';return}if(sig===signature&&(socket?.readyState===WebSocket.OPEN||socket?.readyState===WebSocket.CONNECTING))return;signature=sig;try{socket?.close();const streams=symbols.map(x=>`${x.toLowerCase()}@ticker`).join('/');socket=new WebSocket(`${WS}?streams=${streams}`);socket.onmessage=e=>{try{const d=JSON.parse(e.data).data||{};if(d.s&&d.c)prices.set(d.s,Number(d.c))}catch{}};socket.onclose=()=>{retry=setTimeout(connect,2000)}}catch{retry=setTimeout(connect,2000)}}
function fmt(v){return Number(v).toLocaleString('en-IN',{maximumFractionDigits:8})}
function money(v){return `₹${Number(v).toFixed(2)}`}
function update(){try{const s=read(),ps=s.positions||{};if(!Object.keys(ps).length){connect();return}const root=document.getElementById('paper-engine-live');if(root){const text=root.innerHTML;let html=text;for(const p of Object.values(ps)){const price=prices.get(p.symbol);if(!Number.isFinite(price))continue;const pnl=p.side==='BUY'?(price-Number(p.entry))*Number(p.qty):(Number(p.entry)-price)*Number(p.qty);const esc=p.symbol.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');html=html.replace(new RegExp(`(${esc}[^<]{0,180}?Entry\\s+${Number(p.entry)}\\s+·\\s+Current\\s+)[0-9.eE+-]+`,'i'),`$1${fmt(price)}`);html=html.replace(new RegExp(`(${esc}[^<]{0,500}?Unrealised\\s+)[₹]?[-0-9.]+`,'i'),`$1${money(pnl)}`)}if(html!==text)root.innerHTML=html}connect()}catch{}}
connect();setInterval(update,300);window.addEventListener('paper-pnl-update',update);
