const KEY='paper-engine-state-v1';
const WS='wss://fstream.binance.com/stream';
let socket=null,retry=null,prices=new Map(),signature='';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function save(s){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}}
function getPrice(symbol){try{const m=window.__PAPER_LIVE_TICKERS;if(m?.get){const x=m.get(symbol);const p=Number(x?.lastPrice??x?.price??x?.c);if(Number.isFinite(p)&&p>0)return p}}catch{}try{const m=window.__BINANCE_SCANNER_TICKERS,x=m?.[symbol],p=Number(x?.lastPrice??x?.price??x?.c);if(Number.isFinite(p)&&p>0)return p}catch{}return prices.get(symbol)||null}
function connect(){clearTimeout(retry);const s=read(),symbols=Object.keys(s.positions||{}).filter(Boolean),sig=symbols.join(',');if(!symbols.length){signature='';try{socket?.close()}catch{}return}if(sig===signature&&(socket?.readyState===WebSocket.OPEN||socket?.readyState===WebSocket.CONNECTING))return;signature=sig;try{socket?.close();const streams=symbols.map(x=>`${x.toLowerCase()}@ticker`).join('/');socket=new WebSocket(`${WS}?streams=${streams}`);socket.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||m;if(d.s&&d.c)prices.set(d.s,Number(d.c))}catch{}};socket.onclose=()=>{if(signature===sig)retry=setTimeout(connect,2000)}}catch{retry=setTimeout(connect,2000)}}
function addLog(s,text){s.logs=[{time:new Date().toLocaleTimeString(),text},...(s.logs||[])].slice(0,20)}
function closePosition(s,p,price,pnl,reason){s.realised=Number(s.realised||0)+pnl;s.equity=Number(s.equity||10000)+pnl;s.wins=Number(s.wins||0)+(pnl>=0?1:0);s.losses=Number(s.losses||0)+(pnl<0?1:0);const risk=Math.max(Number(p.riskAmount)||Math.abs(Number(p.entry)-Number(p.sl))*Number(p.qty),0.00000001);const r=pnl/risk;s.history=Array.isArray(s.history)?s.history:[];s.history.push({time:Date.now(),symbol:p.symbol,side:p.side,pnl,r,equity:s.equity});if(s.history.length>100)s.history=s.history.slice(-100);delete s.positions[p.symbol];addLog(s,`PAPER EXIT ${p.symbol} · ${pnl>=0?'WIN':'LOSS'} · ${reason} · P&L ₹${pnl.toFixed(2)} · R ${r.toFixed(2)} · equity ₹${s.equity.toFixed(2)}`)}
function update(){try{const s=read(),ps=s.positions||{};if(!Object.keys(ps).length){connect();return}let changed=false,closed=false;for(const p of Object.values(ps)){const price=getPrice(p.symbol);if(!Number.isFinite(price))continue;const pnl=p.side==='BUY'?(price-Number(p.entry))*Number(p.qty):(Number(p.entry)-price)*Number(p.qty);p.current=price;p.unrealised=pnl;p.updated=Date.now();changed=true;const hit=p.side==='BUY'?(price<=Number(p.sl)||price>=Number(p.tp)):(price>=Number(p.sl)||price<=Number(p.tp));if(hit){const reason=p.side==='BUY'?(price<=Number(p.sl)?'SL':'2R TP'):(price>=Number(p.sl)?'SL':'2R TP');closePosition(s,p,price,pnl,reason);closed=true}}if(changed||closed){save(s);window.dispatchEvent(new Event('paper-pnl-update'))}connect()}catch{}}
connect();setInterval(update,300);window.addEventListener('paper-pnl-update',update);
