const KEY='paper-engine-state-v1';
const WS='wss://fstream.binance.com/stream';
let socket=null,retry=null,prices=new Map(),signature='';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function connect(){clearTimeout(retry);const s=read(),symbols=Object.keys(s.positions||{}).filter(Boolean);const sig=symbols.join(',');if(!symbols.length){signature='';return}if(sig===signature&&(socket?.readyState===WebSocket.OPEN||socket?.readyState===WebSocket.CONNECTING))return;signature=sig;try{socket?.close();const streams=symbols.flatMap(x=>[`${x.toLowerCase()}@ticker`,`${x.toLowerCase()}@markPrice@1s`]).join('/');socket=new WebSocket(`${WS}?streams=${streams}`);socket.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||m;if(d.s&&d.c)prices.set(d.s,Number(d.c));else if(d.s&&d.p)prices.set(d.s,Number(d.p))}catch{}};socket.onclose=()=>{if(signature===sig)retry=setTimeout(connect,2000)}}catch{retry=setTimeout(connect,2000)}}
function fmt(v){return Number(v).toLocaleString('en-IN',{maximumFractionDigits:8})}
function money(v){return `₹${Number(v).toFixed(2)}`}
function update(){try{const s=read(),ps=s.positions||{};if(!Object.keys(ps).length){connect();return}let changed=false;for(const p of Object.values(ps)){const price=prices.get(p.symbol);if(!Number.isFinite(price))continue;const pnl=p.side==='BUY'?(price-Number(p.entry))*Number(p.qty):(Number(p.entry)-price)*Number(p.qty);if(p.current!==price||p.unrealised!==pnl){p.current=price;p.unrealised=pnl;p.updated=Date.now();changed=true}}
if(changed)localStorage.setItem(KEY,JSON.stringify(s));
const roots=[document.getElementById('paper-engine-live'),document.getElementById('position-dashboard')].filter(Boolean);for(const root of roots){const text=root.innerHTML;let html=text;for(const p of Object.values(ps)){const price=prices.get(p.symbol);if(!Number.isFinite(price))continue;const pnl=p.side==='BUY'?(price-Number(p.entry))*Number(p.qty):(Number(p.entry)-price)*Number(p.qty);const esc=p.symbol.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&');html=html.replace(new RegExp(`(${esc}[^<]{0,180}?Entry\\s*:?\\s*${Number(p.entry)}\\s*[^<]{0,80}?Current\\s*:?\\s*)[0-9.eE+-]+`,'i'),`$1${fmt(price)}`);html=html.replace(new RegExp(`(${esc}[^<]{0,500}?Live P&L\\s*:?\\s*)₹?[-0-9.]+`,'i'),`$1${money(pnl)}`);html=html.replace(new RegExp(`(${esc}[^<]{0,500}?Unrealised\\s*:?\\s*)₹?[-0-9.]+`,'i'),`$1${money(pnl)}`)}if(html!==text)root.innerHTML=html}
connect()}catch{}}
connect();setInterval(update,300);window.addEventListener('paper-pnl-update',update);
