const START=10000;const KEY='paper-engine-state-v1';const INTERVAL=15000;const MIN_SCORE=75;const RR=2;const DEFAULT_RISK=.005;const MAX_POS=3;const DAILY_LOSS=.03;const COOLDOWN=15*60*1000;
let state=load(),symbols=[],busy=false,cursor=0,ws=null,liveTickers=new Map(),wsRetry=null,candleWS=null,candleCache={},candleSig='',candleRetry=null;
function fresh(){return{equity:START,realised:0,trades:0,wins:0,losses:0,positions:{},cooldown:{},day:new Date().toDateString(),logs:[]}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY))||{})}catch{return fresh()}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function resetDay(){if(state.day!==new Date().toDateString()){state.day=new Date().toDateString();state.realised=0;state.cooldown={};save()}}
async function api(path){try{const r=await fetch(`https://fapi.binance.com${path}`,{cache:'no-store'});if(r.ok)return r.json()}catch{}const r=await fetch(`/api/binance-market?path=${encodeURIComponent(path)}`,{cache:'no-store'});if(!r.ok)throw Error(`Binance ${r.status}`);return r.json()}
function ema(a,p=9){if(!a.length)return 0;const k=2/(p+1);let e=+a[0];for(let i=1;i<a.length;i++)e=+a[i]*k+e*(1-k);return e}
function atr(k,p=14){if(k.length<p+1)return 0;let s=0;for(let i=k.length-p;i<k.length;i++){const h=+k[i][2],l=+k[i][3],pc=+k[i-1][4];s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/p}
function analyse(a,b,c,t){if(a.length<3||b.length<3||c.length<3)return{signal:null,score:null,spike:null,price:+t.lastPrice,atr:0,reason:'WARMING UP'};const x=a.map(z=>+z[4]),y=b.map(z=>+z[4]),z=c.map(q=>+q[4]),v=b.map(q=>+q[5]);const u1=x.at(-1)>ema(x)&&x.at(-1)>x.at(-2),u5=y.at(-1)>ema(y)&&y.at(-1)>y.at(-2),u15=z.at(-1)>ema(z)&&z.at(-1)>z.at(-2),d1=x.at(-1)<ema(x)&&x.at(-1)<x.at(-2),d5=y.at(-1)<ema(y)&&y.at(-1)<y.at(-2),d15=z.at(-1)<ema(z)&&z.at(-1)<z.at(-2),avg=v.slice(-11,-1).reduce((p,q)=>p+q,0)/Math.max(1,v.slice(-11,-1).length),spike=avg?v.at(-1)/avg:0,raw=Math.round(Math.min(Math.abs(+t.priceChangePercent)*8,35)+Math.min(spike*12,30)+((u5&&u15)||(d5&&d15)?35:0)),buy=u1&&u5&&u15&&+t.priceChangePercent>0&&spike>=1.5,sell=d1&&d5&&d15&&+t.priceChangePercent<0&&spike>=1.5,hardTrend=(u5&&u15)||(d5&&d15),hardDir=(u1&&u5&&u15&&+t.priceChangePercent>0)||(d1&&d5&&d15&&+t.priceChangePercent<0),score=(buy||sell)?Math.max(75,raw):Math.min(raw,74);let reason='Entry confirmation missing';if(hardTrend){if(spike<1.5)reason=`Spike ${spike.toFixed(2)}x < 1.50x`;else if(!hardDir)reason='1M confirmation / 24H direction missing'}else reason='5M + 15M trend confirmation missing';return{signal:buy?'BUY':sell?'SELL':null,score,spike,price:+t.lastPrice,atr:atr(b),trend1:u1?'BULLISH':d1?'BEARISH':'WAIT',trend5:u5?'BULLISH':d5?'BEARISH':'WAIT',trend15:u15?'BULLISH':d15?'BEARISH':'WAIT',reason}}
function risk(){const v=Number(localStorage.getItem('engine-risk')||DEFAULT_RISK*100);return Math.min(.01,Math.max(.001,v/100))}
function addLog(text){state.logs=[{time:new Date().toLocaleTimeString(),text},...(state.logs||[])].slice(0,20);save()}
function qty(price,stop){return +(state.equity*risk()/Math.max(price*stop,.00000001)).toFixed(6)}
function openTrade(t,a){if(!a.signal||a.score<MIN_SCORE||Object.keys(state.positions).length>=MAX_POS||Date.now()<(state.cooldown[t.symbol]||0))return;const stop=Math.max(.008,a.atr/a.price*1.2),q=qty(a.price,stop);if(!q)return;const sl=a.signal==='BUY'?a.price*(1-stop):a.price*(1+stop),tp=a.signal==='BUY'?a.price*(1+stop*RR):a.price*(1-stop*RR);state.positions[t.symbol]={symbol:t.symbol,side:a.signal,qty:q,entry:a.price,current:a.price,sl,tp,opened:Date.now(),score:a.score,spike:a.spike,atr:a.atr,stopPct:stop,unrealised:0};state.cooldown[t.symbol]=Date.now()+COOLDOWN;state.trades++;addLog(`PAPER ENTRY ${t.symbol} ${a.signal} · score ${a.score} · spike ${a.spike.toFixed(2)}x · entry ${a.price} · SL ${sl} · TP ${tp} · qty ${q}`)}
function manage(){for(const p of Object.values(state.positions)){const cached=liveTickers.get(p.symbol);if(!cached)continue;const price=+cached.lastPrice;p.current=price;p.unrealised=p.side==='BUY'?(price-p.entry)*p.qty:(p.entry-price)*p.qty;p.updated=Date.now();const hit=p.side==='BUY'?(price<=p.sl||price>=p.tp):(price>=p.sl||price<=p.tp);if(!hit)continue;const pnl=p.unrealised;state.realised+=pnl;state.equity=START+state.realised;pnl>=0?state.wins++:state.losses++;const reason=p.side==='BUY'?(price<=p.sl?'SL':'2R TP'):(price>=p.sl?'SL':'2R TP');delete state.positions[p.symbol];addLog(`PAPER EXIT ${p.symbol} · ${pnl>=0?'WIN':'LOSS'} · ${reason} · P&L ₹${pnl.toFixed(2)} · equity ₹${state.equity.toFixed(2)}`)}save()}
function startWS(){try{ws?.close();ws=new WebSocket('wss://fstream.binance.com/market/ws');ws.onopen=()=>ws.send(JSON.stringify({method:'SUBSCRIBE',params:['!ticker@arr'],id:77}));ws.onmessage=e=>{try{const m=JSON.parse(e.data),data=Array.isArray(m)?m:(Array.isArray(m.data)?m.data:[]),valid=data.filter(x=>x&&/USDT$/.test(x.s)&&(x.st==null||x.st===1));if(valid.length){symbols=Array.from(new Set([...symbols,...valid.map(x=>x.s)]));valid.forEach(x=>liveTickers.set(x.s,{symbol:x.s,lastPrice:x.c,priceChangePercent:x.P,quoteVolume:x.q}))}}catch{}};ws.onclose=()=>{clearTimeout(wsRetry);wsRetry=setTimeout(startWS,3000)}}catch{}}
function startCandleWS(list){const sig=list.join(',');if(sig===candleSig)return;candleSig=sig;clearTimeout(candleRetry);try{candleWS?.close();const streams=list.flatMap(s=>['1m','5m','15m'].map(iv=>`${s.toLowerCase()}@kline_${iv}`));if(!streams.length)return;const w=new WebSocket(`wss://fstream.binance.com/market/stream?streams=${streams.join('/')}`);candleWS=w;w.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||m;if(d.e!=='kline'||!d.k)return;const s=d.s,iv=d.k.i,row=[d.k.t,d.k.o,d.k.h,d.k.l,d.k.c,d.k.v,d.k.T,d.k.q,d.k.n,d.k.V,d.k.Q,d.k.B];candleCache[s]??={};const arr=candleCache[s][iv]||[],idx=arr.findIndex(x=>x[0]===row[0]);if(idx>=0)arr[idx]=row;else arr.push(row);candleCache[s][iv]=arr.slice(-40)}catch{}};w.onclose=()=>{clearTimeout(candleRetry);candleRetry=setTimeout(()=>{candleSig=''},5000)}}catch{candleSig=''}}
async function seedCandles(list){for(const s of list){candleCache[s]??={};for(const iv of ['1m','5m','15m']){if(candleCache[s][iv]?.length>=30)continue;try{const k=await api(`/fapi/v1/klines?symbol=${s}&interval=${iv}&limit=30`);if(Array.isArray(k)&&k.length)candleCache[s][iv]=k.slice(-40)}catch{}}}}
async function scan(){resetDay();if(state.realised<=-START*DAILY_LOSS)return;const ranked=symbols.map(s=>liveTickers.get(s)).filter(Boolean).sort((a,b)=>+b.quoteVolume-+a.quoteVolume);if(!ranked.length)return;const top=ranked.slice(0,40);await seedCandles(top.map(x=>x.symbol));startCandleWS(top.map(x=>x.symbol));const batch=[];for(let i=0;i<Math.min(10,ranked.length);i++)batch.push(ranked[(cursor+i)%ranked.length]);cursor=(cursor+batch.length)%ranked.length;for(const t of batch){if(Object.keys(state.positions).length>=MAX_POS)break;const c=candleCache[t.symbol]||{};if(!c['1m']||!c['5m']||!c['15m'])continue;const a=analyse(c['1m'],c['5m'],c['15m'],t);if(a.signal&&a.score>=MIN_SCORE)openTrade(t,a)}save()}
function syncMainDashboard(){try{const equityText=`₹${state.equity.toLocaleString('en-IN',{maximumFractionDigits:2})}`;document.querySelectorAll('h2').forEach(el=>{if(el.textContent.trim()==='₹10,000'||el.dataset.paperEquity==='1'){el.textContent=equityText;el.dataset.paperEquity='1'}})}catch{}}
function panel(){let p=document.getElementById('paper-engine-live');if(!p){p=document.createElement('section');p.id='paper-engine-live';p.style='margin:12px auto;max-width:1400px;padding:14px 16px;border:1px solid rgba(0,255,180,.25);border-radius:16px;background:linear-gradient(135deg,#071a18,#111827);color:#fff;font-family:Arial,sans-serif;box-sizing:border-box';document.body.insertBefore(p,document.getElementById('root'))}const ps=Object.values(state.positions);p.innerHTML=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px"><div><b>🧪 PAPER ENGINE</b><h2 style="margin:5px 0">🟢 RUNNING</h2><small>Automatic simulation · no real orders</small></div><div><b>💰 VIRTUAL EQUITY</b><h2 style="margin:5px 0">₹${state.equity.toLocaleString('en-IN',{maximumFractionDigits:2})}</h2><small>Start ₹10,000 · Realised P&L ₹${state.realised.toFixed(2)}</small></div><div><b>📊 PAPER TRADES</b><h2 style="margin:5px 0">${state.trades}</h2><small>Closed wins ${state.wins} · Closed losses ${state.losses}</small></div><div><b>📌 OPEN POSITIONS</b><h2 style="margin:5px 0">${ps.length}/${MAX_POS}</h2><small>Risk ${(risk()*100).toFixed(1)}% · Score ≥ ${MIN_SCORE}</small></div></div><div style="margin-top:12px"><b>📌 OPEN POSITION DETAILS</b>${ps.length?ps.map(q=>`<div style="margin-top:7px;padding:9px;border:1px solid rgba(255,255,255,.12);border-radius:10px"><b>${q.side==='BUY'?'🟢':'🔴'} ${q.symbol}</b> · Entry ${q.entry} · Current ${q.current} · SL ${q.sl} · TP ${q.tp} · Qty ${q.qty} · Unrealised ₹${(q.unrealised||0).toFixed(2)}</div>`).join(''):'<div style="opacity:.8;margin-top:6px">No open paper position.</div>'}</div><div style="margin-top:10px;font-size:12px;opacity:.9"><b>LIVE PAPER LOG:</b> ${(state.logs?.[0]?.time||'—')} ${(state.logs?.[0]?.text||'Waiting for first qualifying signal…')}</div>`;syncMainDashboard()}
async function loop(){if(busy)return;busy=true;try{manage();if((localStorage.getItem('engine-mode')||'PAPER')==='PAPER')await scan();panel()}catch(e){panel();console.warn('Paper engine',e)}finally{busy=false}}async function init(){try{const e=await api('/fapi/v1/exchangeInfo');symbols=Array.from(new Set([...symbols,...e.symbols.filter(s=>s.contractType==='PERPETUAL'&&s.quoteAsset==='USDT'&&s.status==='TRADING').map(s=>s.symbol)]))}catch{}startWS();panel();loop();setInterval(loop,INTERVAL)}setTimeout(init,1200);