const SCALP_KEY='scalping-paper-state-v1';
const START=10000,RISK=.005,RR=1.5,MAX_POS=3,MIN_SCORE=70,SCAN=30000,MAX_CANDLES=60;
const WS='wss://fstream.binance.com/market/ws';
const esc=s=>String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const num=v=>Number(v)||0;
const ema=(a,p=9)=>{if(!a.length)return 0;const k=2/(p+1);let e=num(a[0]);for(let i=1;i<a.length;i++)e=num(a[i])*k+e*(1-k);return e};
const atr=(k,p=14)=>{if(k.length<p+1)return 0;let s=0;for(let i=k.length-p;i<k.length;i++){const h=num(k[i][2]),l=num(k[i][3]),pc=num(k[i-1][4]);s+=Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))}return s/p};
function analyse(k1,k5,t){if(k1.length<20||k5.length<20)return{score:null,signal:'WAIT',reason:`WARMING · ${k1.length}/20 1M · ${k5.length}/20 5M`,sl:0,tp:0,spike:0};const c1=k1.map(x=>num(x[4])),c5=k5.map(x=>num(x[4])),v1=k1.map(x=>num(x[5]));const e1=ema(c1,9),e5=ema(c5,9),r1=c1.at(-1),r5=c5.at(-1),p1=c1.at(-2);const bull1=r1>e1&&r1>p1,bear1=r1<e1&&r1<p1,bull5=r5>e5,bear5=r5<e5;const base=v1.slice(-11,-1).reduce((a,b)=>a+b,0)/Math.max(1,v1.slice(-11,-1).length),spike=base?v1.at(-1)/base:0,chg=num(t.priceChangePercent);const score=Math.round(Math.min(Math.abs(chg)*10,30)+Math.min(spike*15,30)+((bull1&&bull5)||(bear1&&bear5)?40:0));const buy=bull1&&bull5&&chg>0&&spike>=1.25,sell=bear1&&bear5&&chg<0&&spike>=1.25;const a=Math.max(atr(k1),r1*.0015);const signal=(buy||sell)&&score>=MIN_SCORE?(buy?'BUY':'SELL'):'WAIT';let reason='Entry confirmation missing';if(!((bull1&&bull5)||(bear1&&bear5)))reason='5M trend + 1M momentum missing';else if(spike<1.25)reason=`Volume spike ${spike.toFixed(2)}x < 1.25x`;else if((buy||sell)&&score<MIN_SCORE)reason=`Score ${score} < ${MIN_SCORE}`;else if(!buy&&!sell)reason='24H direction confirmation missing';return{score,signal,reason,spike,sl:signal==='BUY'?r1-a:r1+a,tp:signal==='BUY'?r1+a*RR:r1-a*RR,atr:a}}
function readState(){try{return JSON.parse(localStorage.getItem(SCALP_KEY)||'null')||{equity:START,realized:0,trades:0,wins:0,losses:0,open:[]}}catch{return{equity:START,realized:0,trades:0,wins:0,losses:0,open:[]}}}
function saveState(s){try{localStorage.setItem(SCALP_KEY,JSON.stringify(s))}catch{}}
function mount(){if(document.getElementById('scalping-engine-panel'))return document.getElementById('scalping-engine-panel');const el=document.createElement('section');el.id='scalping-engine-panel';el.style.cssText='margin:12px auto 0;max-width:1400px;padding:16px;border:2px solid #ffd24a;border-radius:18px;background:linear-gradient(135deg,#17120a,#21182d);color:#fff;font-family:Arial,sans-serif;box-sizing:border-box;box-shadow:0 0 35px #ffb30044';el.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><b style="font-size:18px;color:#ffd24a">⚡ SCALPING ENGINE — PAPER</b><div style="opacity:.8;font-size:12px;margin-top:4px">1M + 5M momentum · volume spike ≥1.25x · 24H direction · ATR SL · 1.5R TP · real orders OFF</div></div><div id="scalp-status" style="font-weight:900">🟡 STARTING…</div></div><div id="scalp-stats" style="display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px"></div><div id="scalp-list" style="margin-top:12px;display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px"></div>`;document.body.insertBefore(el,document.getElementById('root'));return el}
const tickerMap=new Map();const candleMap=new Map();let tickerWS=null,candleWS=null,tickerWaiters=[];let subscribed=new Set();let lastTopKey='';
function parseArray(raw){return Array.isArray(raw)?raw:(raw&&Array.isArray(raw.data)?raw.data:raw&&raw.data?[raw.data]:raw?[raw]:[])}
function startTicker(){if(tickerWS&&(tickerWS.readyState===0||tickerWS.readyState===1))return;try{tickerWS=new WebSocket(WS);tickerWS.onopen=()=>{try{tickerWS.send(JSON.stringify({method:'SUBSCRIBE',params:['!ticker@arr'],id:Date.now()}))}catch{}};tickerWS.onmessage=e=>{try{for(const x of parseArray(JSON.parse(e.data))){if(x&&x.s&&/USDT$/.test(x.s))tickerMap.set(x.s,{symbol:x.s,lastPrice:num(x.c),priceChangePercent:num(x.P),quoteVolume:num(x.q)})}if(tickerMap.size&&tickerWaiters.length){const w=tickerWaiters.splice(0);w.forEach(fn=>fn())}}catch{}};tickerWS.onclose=()=>{tickerWS=null;setTimeout(startTicker,2000)};tickerWS.onerror=()=>{try{tickerWS.close()}catch{}}}catch{setTimeout(startTicker,2000)}}
function waitForTickers(ms=10000){if(tickerMap.size)return Promise.resolve();return new Promise(resolve=>{const t=setTimeout(()=>{tickerWaiters=[];resolve()},ms);tickerWaiters.push(()=>{clearTimeout(t);resolve()})})}
function liveTop(){return [...tickerMap.values()].filter(x=>/USDT$/.test(x.symbol)&&x.quoteVolume>0).sort((a,b)=>b.quoteVolume-a.quoteVolume).slice(0,20)}
function key(symbol,interval){return `${symbol}:${interval}`}
function pushCandle(symbol,interval,k){const id=key(symbol,interval);let a=candleMap.get(id)||[];const row=[num(k.t),num(k.o),num(k.h),num(k.l),num(k.c),num(k.v),!!k.x];const last=a.at(-1);if(last&&last[0]===row[0])a[a.length-1]=row;else a.push(row);if(a.length>MAX_CANDLES)a=a.slice(-MAX_CANDLES);candleMap.set(id,a)}
function subscribeCandles(top){const next=new Set();for(const t of top){next.add(key(t.symbol,'1m'));next.add(key(t.symbol,'5m'))}const params=[...next].filter(k=>!subscribed.has(k)).map(k=>{const [s,i]=k.split(':');return `${s.toLowerCase()}@kline_${i}`});if(candleWS&&candleWS.readyState===1&&params.length){try{candleWS.send(JSON.stringify({method:'SUBSCRIBE',params,id:Date.now()}));for(const p of params)subscribed.add(p.split('@')[0].toUpperCase()+'|'+p.split('_').pop())}catch{}}}
function startCandles(){if(candleWS&&(candleWS.readyState===0||candleWS.readyState===1))return;try{candleWS=new WebSocket(WS);candleWS.onopen=()=>{subscribed=new Set();subscribeCandles(liveTop())};candleWS.onmessage=e=>{try{for(const x of parseArray(JSON.parse(e.data))){const d=x?.k||x?.data?.k;if(d&&d.s&&d.i)pushCandle(d.s,d.i,d)}}catch{}};candleWS.onclose=()=>{candleWS=null;subscribed=new Set();setTimeout(startCandles,2500)};candleWS.onerror=()=>{try{candleWS.close()}catch{}}}catch{setTimeout(startCandles,2500)}}
function updateSubscriptions(top){const k=top.map(t=>t.symbol).join(',');if(k===lastTopKey)return;lastTopKey=k;subscribeCandles(top)}
function warmStatus(top){let ready=0,total=top.length;for(const t of top){if((candleMap.get(key(t.symbol,'1m'))||[]).length>=20&&(candleMap.get(key(t.symbol,'5m'))||[]).length>=20)ready++}return{ready,total}}
let running=false;
function render(root,out,state,status,top){const stats=root.querySelector('#scalp-stats'),list=root.querySelector('#scalp-list');const buy=out.filter(x=>x.signal==='BUY').length,sell=out.filter(x=>x.signal==='SELL').length;const w=warmStatus(top);status.textContent=w.ready===w.total?`🟢 ACTIVE · ${w.ready}/${w.total} ready · ${buy} BUY · ${sell} SELL`:`🟡 WARMING · ${w.ready}/${w.total} ready · live candles collecting`;stats.innerHTML=[['₹'+state.equity.toFixed(2),'SCALP EQUITY'],['₹'+state.realized.toFixed(2),'REALIZED P&L'],[state.trades,'ENTRIES'],[state.wins+'W / '+state.losses+'L','RESULT'],[state.open.length+'/'+MAX_POS,'OPEN']].map(x=>`<div style="padding:10px;border-radius:10px;background:#ffffff12;border:1px solid #ffffff20"><b style="font-size:16px">${x[0]}</b><small style="display:block;opacity:.7;margin-top:3px">${x[1]}</small></div>`).join('');const candidates=out.filter(x=>x.signal!=='WAIT').sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,8);list.innerHTML=(candidates.length?candidates:out.slice(0,8)).map(x=>`<div style="padding:11px;border-radius:11px;background:${x.signal==='BUY'?'#005b3a':x.signal==='SELL'?'#72002c':'#ffffff0d'};border:1px solid #ffffff20"><b>${esc(x.symbol)}</b><span style="float:right;font-weight:900">${x.signal}</span><div style="margin-top:5px;font-size:12px">Score ${x.score??'—'} · Spike ${x.spike!=null?x.spike.toFixed(2):'—'}x · 24H ${num(x.priceChangePercent).toFixed(2)}%</div><div style="font-size:11px;opacity:.75;margin-top:4px">${esc(x.reason)}</div></div>`).join('')||'<div style="opacity:.7">Waiting for live 1M/5M candle data.</div>'}
async function run(){if(running)return;running=true;const root=mount(),status=root.querySelector('#scalp-status');try{startTicker();startCandles();status.textContent='🟡 CONNECTING · live Binance feeds…';await waitForTickers(10000);const top=liveTop();if(!top.length){status.textContent='🟠 WAITING · live market feed retry';return}updateSubscriptions(top);const out=[];for(const t of top){const k1=candleMap.get(key(t.symbol,'1m'))||[],k5=candleMap.get(key(t.symbol,'5m'))||[];if(k1.length>=20&&k5.length>=20)out.push({...t,...analyse(k1,k5,t)});else out.push({...t,...analyse(k1,k5,t)})}const state=readState(),now=Date.now(),prices=new Map([...tickerMap.values()].map(x=>[x.symbol,num(x.lastPrice)]));state.open=(state.open||[]).filter(p=>{const px=prices.get(p.symbol)||p.entry;const hit=p.side==='BUY'?(px<=p.sl||px>=p.tp):(px>=p.sl||px<=p.tp);if(!hit)return true;const pnl=(p.side==='BUY'?px-p.entry:p.entry-px)*p.qty;state.equity+=pnl;state.realized+=pnl;state.wins+=pnl>0?1:0;state.losses+=pnl<=0?1:0;return false});for(const x of out.filter(x=>x.signal!=='WAIT').sort((a,b)=>(b.score||0)-(a.score||0))){if(state.open.length>=MAX_POS)break;if(state.open.some(p=>p.symbol===x.symbol))continue;const live=tickerMap.get(x.symbol),entry=num(live?.lastPrice)||num(x.lastPrice),dist=Math.max(Math.abs(x.sl-num(x.price||x.lastPrice)),entry*.0005),riskCash=state.equity*RISK,side=x.signal;const sl=side==='BUY'?entry-dist:entry+dist,tp=side==='BUY'?entry+dist*RR:entry-dist*RR;state.open.push({symbol:x.symbol,side,entry,qty:riskCash/dist,sl,tp,openedAt:now});state.trades++}saveState(state);render(root,out,state,status,top)}catch(e){status.textContent='🟠 WAITING · live feed retrying…'}finally{running=false}}
mount();startTicker();startCandles();run();setInterval(run,SCAN);
