const K='scalping-paper-state-v3',OLD='scalping-paper-state-v2',AK='scalping-analysis-v1',START=10000,RISK=.005,RR=1.5,MAX=3,MIN=75,VOL=1.25,COOL=9e5,GUARD=.03,SCAN=3e4,BATCH=24,LIM=80;
const N=v=>Number(v)||0,E=s=>String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m])),ID=(s,i)=>s+':'+i;
async function get(p){for(const u of ['/api/binance-market?path='+encodeURIComponent(p),'https://fapi.binance.com'+p])try{const r=await Promise.race([fetch(u,{cache:'no-store'}),new Promise((_,x)=>setTimeout(()=>x(7000),7000))]);if(r.ok)return await r.json()}catch{}throw Error('market data unavailable')}
const EMA=(a,p=9)=>{if(!a.length)return 0;let k=2/(p+1),e=N(a[0]);for(let i=1;i<a.length;i++)e=N(a[i])*k+e*(1-k);return e},ATR=a=>{if(a.length<15)return 0;let s=0;for(let i=a.length-14;i<a.length;i++){let h=N(a[i][2]),l=N(a[i][3]),p=N(a[i-1][4]);s+=Math.max(h-l,Math.abs(h-p),Math.abs(l-p))}return s/14},closed=a=>a?.length&&a.at(-1)?.[6]===false?a.slice(0,-1):(a||[]);
function analyse(a,b,c,t){a=closed(a);b=closed(b);c=closed(c);if(!t?.valid)return{signal:'WAIT',score:null,reason:'WAIT · ticker data unavailable',spike:0};if(a.length<20||b.length<20||c.length<20)return{signal:'WAIT',score:null,reason:'WARMING',spike:0};let ca=a.map(x=>N(x[4])),cb=b.map(x=>N(x[4])),cc=c.map(x=>N(x[4])),v=a.map(x=>N(x[5])),r=ca.at(-1),bull=r>EMA(ca)&&r>ca.at(-2)&&cb.at(-1)>EMA(cb)&&cb.at(-1)>=cb.at(-2)&&cc.at(-1)>EMA(cc),bear=r<EMA(ca)&&r<ca.at(-2)&&cb.at(-1)<EMA(cb)&&cb.at(-1)<=cb.at(-2)&&cc.at(-1)<EMA(cc),base=v.slice(-11,-1).reduce((x,y)=>x+y,0)/10,sp=base?v.at(-1)/base:0,ch=Number(t.priceChangePercent),dir=ch>0?'BUY':ch<0?'SELL':'WAIT',trend=bull?'BUY':bear?'SELL':'WAIT',score=Math.round(Math.min(Math.abs(ch)*10,25)+Math.min(sp*15,30)+(trend!=='WAIT'?35:0)+(dir===trend?10:0)),sig=trend===dir&&sp>=VOL&&score>=MIN?trend:'WAIT',why=sig!=='WAIT'?'READY · 1M + 5M + 15M + 24H + volume confirmed':trend==='WAIT'?'WAIT · trend alignment missing':sp<VOL?`WAIT · Spike ${sp.toFixed(2)}x < ${VOL}x`:dir!==trend?'WAIT · 24H direction confirmation missing':`WAIT · Score ${score} < ${MIN}`,d=Math.max(ATR(a),r*.0015);return{signal:sig,score,reason:why,spike:sp,sl:sig==='BUY'?r-d:r+d,tp:sig==='BUY'?r+d*RR:r-d*RR}}
const fresh=()=>({equity:START,realized:0,trades:0,wins:0,losses:0,open:[],history:[],dayKey:new Date().toISOString().slice(0,10),dayStartEquity:START,dayRealized:0});
function state(){try{let s=JSON.parse(localStorage.getItem(K)||'null')||JSON.parse(localStorage.getItem(OLD)||'null')||fresh();s={...fresh(),...s};s.open=Array.isArray(s.open)?s.open:[];s.history=Array.isArray(s.history)?s.history:[];s.equity=N(s.equity)||START;s.dayStartEquity=N(s.dayStartEquity)||s.equity;s.realized=s.equity-START;s.dayRealized=s.equity-s.dayStartEquity;return s}catch{return fresh()}}
function save(s){s.realized=s.equity-START;s.dayRealized=s.equity-s.dayStartEquity;s.history=s.history.slice(-100);localStorage.setItem(K,JSON.stringify(s))}
function universe(){try{let a=JSON.parse(localStorage.getItem('scanner-universe-v1')||'[]');return[...new Set(a.map(x=>String(x).trim().toUpperCase()).filter(x=>x.endsWith('USDT')))].sort()}catch{return[]}}
const tick=new Map(),c=new Map();let tw,ws,sub=new Set(),subSymbols=new Set(),off=0,busy=0;
function tickerObject(x){let s=String(x?.s||x?.symbol||'').trim().toUpperCase(),p=Number(x?.c??x?.lastPrice??x?.lastPrice),q=Number(x?.q??x?.quoteVolume),pc=Number(x?.P??x?.priceChangePercent);if(!s.endsWith('USDT')||!Number.isFinite(p)||!Number.isFinite(pc)||p<=0)return null;return{symbol:s,lastPrice:p,priceChangePercent:pc,quoteVolume:Number.isFinite(q)&&q>=0?q:0,valid:true}}
function putTicker(x){let t=tickerObject(x);if(t)tick.set(t.symbol,t)}
function tickerPayload(x){if(Array.isArray(x))return x;return Array.isArray(x?.data)?x.data:Array.isArray(x?.result)?x.result:(x?.data?.s||x?.data?.symbol)?[x.data]:x?.s||x?.symbol?[x]:[]}
async function refreshTickers(){try{let a=await get('/fapi/v1/ticker/24hr');for(const x of tickerPayload(a))putTicker(x)}catch{}}
async function ensureTickers(ss){let missing=ss.filter(s=>!tick.get(s)?.valid);for(let i=0;i<missing.length;i+=8)await Promise.all(missing.slice(i,i+8).map(async s=>{try{let x=await get(`/fapi/v1/ticker/24hr?symbol=${encodeURIComponent(s)}`);for(const y of tickerPayload(x))putTicker(y)}catch{}}))}
function ticker(){if(tw&&(tw.readyState<2))return;try{tw=new WebSocket('wss://fstream.binance.com/ws/!ticker@arr');tw.onmessage=e=>{try{for(const x of tickerPayload(JSON.parse(e.data)))putTicker(x)}catch{}};tw.onclose=()=>{tw=null;setTimeout(ticker,2e3)};tw.onerror=()=>{try{tw.close()}catch{}}}catch{}}
function push(s,i,k){let id=ID(s,i),a=c.get(id)||[],r=[N(k.t),N(k.o),N(k.h),N(k.l),N(k.c),N(k.v),!!k.x];if(a.at(-1)?.[0]===r[0])a[a.length-1]=r;else a.push(r);c.set(id,a.slice(-LIM))}
function seed(s,i,a){if(a?.length)c.set(ID(s,i),a.map(k=>[N(k[0]),N(k[1]),N(k[2]),N(k[3]),N(k[4]),N(k[5]),true]).slice(-LIM))}
async function hydrate(ss){for(let i=0;i<ss.length;i+=6){await Promise.all(ss.slice(i,i+6).map(async s=>{try{let[a,b,d]=await Promise.all([get(`/fapi/v1/klines?symbol=${s}&interval=1m&limit=45`),get(`/fapi/v1/klines?symbol=${s}&interval=5m&limit=45`),get(`/api/binance-market?path=${encodeURIComponent(`/fapi/v1/klines?symbol=${s}&interval=15m&limit=45`)}`)]);seed(s,'1m',a);seed(s,'5m',b);seed(s,'15m',d)}catch{try{let[a,b,d]=await Promise.all([get(`/fapi/v1/klines?symbol=${s}&interval=1m&limit=45`),get(`/fapi/v1/klines?symbol=${s}&interval=5m&limit=45`),get(`/fapi/v1/klines?symbol=${s}&interval=15m&limit=45`)]);seed(s,'1m',a);seed(s,'5m',b);seed(s,'15m',d)}catch{}}}))}}
function socket(){if(ws&&(ws.readyState<2))return;try{ws=new WebSocket('wss://fstream.binance.com/stream');ws.onopen=()=>{sub=new Set();subSymbols=new Set()};ws.onmessage=e=>{try{let x=JSON.parse(e.data),k=x?.k||x?.data?.k;if(k?.s&&k?.i)push(k.s,k.i,k)}catch{}};ws.onclose=()=>{ws=null;sub=new Set();subSymbols=new Set();setTimeout(socket,2500)};ws.onerror=()=>{try{ws.close()}catch{}}}catch{}}
function subscribe(ss){if(!ws||ws.readyState!==1)return;let next=[...new Set(ss)],old=[...subSymbols],oldParams=[];for(const s of old)for(const i of ['1m','5m','15m'])oldParams.push(`${s.toLowerCase()}@kline_${i}`);if(oldParams.length)try{ws.send(JSON.stringify({method:'UNSUBSCRIBE',params:oldParams,id:Date.now()}))}catch{}sub=new Set();subSymbols=new Set(next);let p=[];for(const s of next)for(const i of ['1m','5m','15m']){p.push(`${s.toLowerCase()}@kline_${i}`);sub.add(ID(s,i))}if(p.length)try{ws.send(JSON.stringify({method:'SUBSCRIBE',params:p,id:Date.now()+1}))}catch{}}
function loadAnalysis(){try{let x=JSON.parse(localStorage.getItem(AK)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
function saveAnalysis(o){try{let a=loadAnalysis(),now=Date.now();for(const x of o)if(x?.symbol)a[x.symbol]={...a[x.symbol],...x,analyzedAt:now};let keys=Object.keys(a);if(keys.length>900)keys.sort((x,y)=>(a[y].analyzedAt||0)-(a[x].analyzedAt||0)).slice(900).forEach(k=>delete a[k]);localStorage.setItem(AK,JSON.stringify(a))}catch{}}
function mergeLive(x){let t=tick.get(x.symbol);return t?{...x,...t}:x}
function mount(){let e=document.getElementById('scalping-engine-panel');if(e)return e;e=document.createElement('section');e.id='scalping-engine-panel';e.style.cssText='margin:16px auto;max-width:1500px;padding:22px;border:3px solid #ffd24a;border-radius:22px;background:linear-gradient(135deg,#17120a,#21182d);color:#fff;font-family:Arial,sans-serif;box-shadow:0 0 35px #ffb30044';e.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><b style="font-size:24px;color:#ffd24a">⚡ SCALPING ENGINE — PAPER</b><div style="font-size:14px;opacity:.85;margin-top:6px">1M + 5M + 15M momentum · volume spike ≥1.25x · 24H direction · ATR SL · 1.5R TP · real orders OFF</div></div><div id="scalp-status" style="font-size:15px;font-weight:900">🟡 STARTING…</div></div><div id="scalp-stats" style="display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:16px"></div><div id="scalp-list" style="margin-top:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:10px"></div><div id="scalp-history" style="margin-top:18px"></div>';document.body.insertBefore(e,document.getElementById('root'));return e}
function history(s){let h=s.history.slice().reverse().slice(0,10);if(!h.length)return'<div style="font-size:14px;opacity:.7">No closed scalping trades yet.</div>';return`<div style="font-size:17px;font-weight:900;color:#ffd24a;margin-bottom:9px">🧾 SCALPING TRADE HISTORY · ${s.history.length} CLOSED</div><div style="overflow:auto"><table style="min-width:1000px;width:100%;font-size:14px;border-collapse:collapse"><thead><tr>${['TIME','COIN','SIDE','ENTRY','EXIT','P&L','R','SL','TP','DURATION','RESULT','REASON'].map(x=>`<th style="padding:9px;text-align:left">${x}</th>`).join('')}</tr></thead><tbody>${h.map(x=>{let r=Number.isFinite(+x.r)?`${x.r>=0?'+':''}${x.r.toFixed(2)}R`:'—',d=x.durationMs>0?Math.max(1,Math.round(x.durationMs/6e4))+'m':'—';return`<tr><td style="padding:9px">${E(new Date(x.closedAt||x.time).toLocaleTimeString('en-IN',{hour12:false}))}</td><td style="padding:9px">${E(x.symbol)}</td><td style="padding:9px">${x.side}</td><td style="padding:9px">${N(x.entry)}</td><td style="padding:9px">${N(x.exit)}</td><td style="padding:9px">₹${N(x.pnl).toFixed(2)}</td><td style="padding:9px">${r}</td><td style="padding:9px">${N(x.sl)||'—'}</td><td style="padding:9px">${N(x.tp)||'—'}</td><td style="padding:9px">${d}</td><td style="padding:9px">${x.pnl>0?'WIN':'LOSS'}</td><td style="padding:9px">${E(x.reason||'SL/TP')}</td></tr>`}).join('')}</tbody></table></div>`}
function render(root,o,s,u){let b=o.filter(x=>x.signal==='BUY').length,sel=o.filter(x=>x.signal==='SELL').length,cache=loadAnalysis(),analysed=Object.keys(cache).filter(k=>u.includes(k)).length;root.querySelector('#scalp-status').textContent=`🟢 ACTIVE · ${analysed}/${u.length} ANALYZED · ${b} BUY · ${sel} SELL · full-universe rotation`;root.querySelector('#scalp-stats').innerHTML=[['₹'+s.equity.toFixed(2),'SCALP EQUITY'],['₹'+s.realized.toFixed(2),'REALIZED P&L'],[s.trades,'ENTRIES'],[s.wins+'W / '+s.losses+'L','RESULT'],[s.open.length+'/'+MAX,'OPEN'],[u.length,'MARKET COINS']].map(x=>`<div style="padding:14px;background:#ffffff12;border-radius:12px"><b style="font-size:20px">${x[0]}</b><small style="display:block;font-size:12px;opacity:.7;margin-top:3px">${x[1]}</small></div>`).join('');let all=Object.values(cache).filter(x=>u.includes(x.symbol)).map(mergeLive);let shown=[...o.map(mergeLive),...all.filter(x=>!o.some(y=>y.symbol===x.symbol))].sort((a,b)=>(b.score||-1)-(a.score||-1)).slice(0,20);let ready=shown.filter(x=>x.signal!=='WAIT');root.querySelector('#scalp-list').innerHTML=(ready.length?ready:shown).map(x=>`<div style="padding:14px;border-radius:12px;background:${x.signal==='BUY'?'#005b3a':x.signal==='SELL'?'#72002c':'#ffffff0d'}"><b style="font-size:17px">${E(x.symbol)}</b><span style="float:right;font-weight:900;font-size:15px">${E(x.signal||'WAIT')}</span><div style="font-size:14px;margin-top:7px">Price ${x.valid?N(x.lastPrice):'—'} · Score ${x.score??'—'} · Spike ${Number(x.spike||0).toFixed(2)}x</div><div style="font-size:13px;margin-top:4px">24H ${x.valid?N(x.priceChangePercent).toFixed(2):'—'}% · Vol ${x.valid?'$'+(N(x.quoteVolume)/1e6).toFixed(2)+'M':'—'}</div><small style="font-size:12px;display:block;margin-top:5px">${E(x.reason||'Waiting for rotating candle analysis')}</small></div>`).join('');root.querySelector('#scalp-history').innerHTML=history(s)}
async function run(){if(busy)return;busy=1;let root=mount();try{ticker();socket();let u=universe();if(!u.length){root.querySelector('#scalp-status').textContent='🟠 WAITING · stable universe not ready';return}await refreshTickers();let n=u.length,ss=[];for(let i=0;i<Math.min(BATCH,n);i++)ss.push(u[(off+i)%n]);off=(off+BATCH)%n;let hot=[...tick.values()].filter(x=>x.valid).sort((a,b)=>Math.abs(b.priceChangePercent)-Math.abs(a.priceChangePercent)).slice(0,8).map(x=>x.symbol);ss=[...new Set([...ss,...hot])];await ensureTickers(ss);await hydrate(ss);subscribe(ss);let o=ss.map(x=>{let t=tick.get(x)||{symbol:x,lastPrice:0,priceChangePercent:0,quoteVolume:0,valid:false};return{...t,...analyse(c.get(ID(x,'1m'))||[],c.get(ID(x,'5m'))||[],c.get(ID(x,'15m'))||[],t)}});saveAnalysis(o);let s=state(),now=Date.now();s.open=s.open.filter(p=>{let px=N(tick.get(p.symbol)?.lastPrice)||p.entry,hit=p.side==='BUY'?(px<=p.sl||px>=p.tp):(px>=p.sl||px<=p.tp);if(!hit)return true;let pnl=(p.side==='BUY'?px-p.entry:p.entry-px)*p.qty,r=p.riskAmount>0?pnl/p.riskAmount:null;s.equity+=pnl;s.wins+=pnl>0;s.losses+=pnl<=0;s.history.push({time:now,closedAt:now,symbol:p.symbol,side:p.side,entry:p.entry,exit:px,pnl,r,sl:p.sl,tp:p.tp,durationMs:now-(p.openedAt||now),riskAmount:p.riskAmount,reason:(p.side==='BUY'?px>=p.tp:px<=p.tp)?'TP':'SL'});return false});let guard=s.equity-s.dayStartEquity<=-s.dayStartEquity*GUARD;for(let x of o.filter(x=>x.signal!=='WAIT'&&x.valid&&x.lastPrice>0).sort((a,b)=>(b.score||0)-(a.score||0))){if(s.open.length>=MAX||guard)break;if(s.open.some(p=>p.symbol===x.symbol))continue;let h=s.history.slice().reverse().find(h=>h.symbol===x.symbol);if(h&&now-(h.closedAt||h.time)<COOL)continue;let entry=N(x.lastPrice),d=Math.max(Math.abs(x.sl-entry),entry*.0005),risk=s.equity*RISK,qty=risk/d;if(!Number.isFinite(qty)||qty<=0)continue;let side=x.signal,sl=side==='BUY'?entry-d:entry+d,tp=side==='BUY'?entry+d*RR:entry-d*RR;s.open.push({symbol:x.symbol,side,entry,sl,tp,qty,riskAmount:risk,openedAt:now,score:x.score,spike:x.spike});s.trades++}save(s);render(root,o,s,u)}catch(e){root.querySelector('#scalp-status').textContent='🟠 ERROR · '+(e.message||'retrying')}finally{busy=0}}
function boot(){mount();run();setInterval(run,SCAN)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();