import crypto from 'crypto';
const BASE='https://fapi.binance.com';
const MAX_NOTIONAL=Number(process.env.LIVE_MAX_NOTIONAL_USDT||100);
const STOP_PCT=Number(process.env.LIVE_STOP_PCT||0.006);
const RR=Number(process.env.LIVE_TP_RR||2);
async function signed(method,path,params){const key=process.env.BINANCE_API_KEY,secret=process.env.BINANCE_API_SECRET;if(!key||!secret)throw Error('Binance server credentials are not configured');const q=new URLSearchParams();for(const [k,v] of Object.entries(params||{})){if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v))}q.set('timestamp',String(Date.now()));q.set('recvWindow','5000');const sig=crypto.createHmac('sha256',secret).update(q.toString()).digest('hex');q.set('signature',sig);const r=await fetch(BASE+path+'?'+q.toString(),{method,headers:{'X-MBX-APIKEY':key,accept:'application/json'},cache:'no-store'});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}};if(!r.ok){const e=Error(data?.msg||data?.error||'Binance request failed');e.status=r.status;e.data=data;throw e}return data}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});if(process.env.LIVE_UNLOCKED!=='true')return res.status(403).json({error:'LIVE execution is locked. Set LIVE_UNLOCKED=true only after testing.'});try{const b=req.body||{},action=b.action||'order';if(action==='order'){const symbol=String(b.symbol||'').trim(),side=String(b.side||''),quantity=Number(b.quantity),type=String(b.type||'MARKET');if(!/^[A-Z0-9_]{5,30}$/.test(symbol))return res.status(400).json({error:'Invalid symbol'});if(!['BUY','SELL'].includes(side))return res.status(400).json({error:'Invalid side'});if(!['MARKET','STOP_MARKET','TAKE_PROFIT_MARKET'].includes(type))return res.status(400).json({error:'Order type not allowed'});if(!Number.isFinite(quantity)||quantity<=0)return res.status(400).json({error:'Invalid quantity'});if(Number(b.price||0)*quantity>MAX_NOTIONAL)return res.status(400).json({error:`Live notional exceeds ${MAX_NOTIONAL} USDT safety cap`});const p={symbol,side,type,quantity:String(quantity)};if(b.reduceOnly!==undefined)p.reduceOnly=String(b.reduceOnly);if(type!=='MARKET'){const sp=Number(b.stopPrice);if(!Number.isFinite(sp)||sp<=0)return res.status(400).json({error:'Invalid stop price'});p.stopPrice=String(sp);p.workingType='MARK_PRICE'}const entry=await signed('POST','/fapi/v1/order',p);let protection=null;if(type==='MARKET'&&String(b.reduceOnly)!=='true'&&process.env.LIVE_PROTECT_ORDERS!=='false'){const fill=Number(entry.avgPrice||b.price);if(fill>0){const sl=side==='BUY'?fill*(1-STOP_PCT):fill*(1+STOP_PCT),tp=side==='BUY'?fill*(1+STOP_PCT*RR):fill*(1-STOP_PCT*RR),exitSide=side==='BUY'?'SELL':'BUY';try{const stop=await signed('POST','/fapi/v1/order',{symbol,side:exitSide,type:'STOP_MARKET',quantity:String(quantity),stopPrice:sl.toString(),reduceOnly:'true',workingType:'MARK_PRICE'});const take=await signed('POST','/fapi/v1/order',{symbol,side:exitSide,type:'TAKE_PROFIT_MARKET',quantity:String(quantity),stopPrice:tp.toString(),reduceOnly:'true',workingType:'MARK_PRICE'});protection={stopOrderId:stop.orderId,takeProfitOrderId:take.orderId,stopPrice:sl,takeProfitPrice:tp}}catch(e){protection={error:e.message,warning:'Entry filled but protective orders were not both accepted'}}}}return res.status(200).json({entry,protection})}
if(action==='close'){const symbol=String(b.symbol||''),side=String(b.side||''),quantity=Number(b.quantity);if(!symbol||!['BUY','SELL'].includes(side)||!Number.isFinite(quantity)||quantity<=0)return res.status(400).json({error:'Invalid close request'});if(Number(b.price||0)*quantity>MAX_NOTIONAL)return res.status(400).json({error:`Close notional exceeds ${MAX_NOTIONAL} USDT safety cap`});return res.status(200).json(await signed('POST','/fapi/v1/order',{symbol,side,type:'MARKET',quantity:String(quantity),reduceOnly:'true'}))}
if(action==='cancelAll'){const symbol=String(b.symbol||'');if(!symbol)return res.status(400).json({error:'Symbol required'});return res.status(200).json(await signed('DELETE','/fapi/v1/allOpenOrders',{symbol}))}
return res.status(400).json({error:'Unsupported trading action'})}catch(e){return res.status(e.status||502).json({error:e.message,binance:e.data||null})}}