import crypto from 'crypto';
const BASE='https://fapi.binance.com';
const MAX_NOTIONAL=Number(process.env.LIVE_MAX_NOTIONAL_USDT||100);
const DEFAULT_STOP=Number(process.env.LIVE_STOP_PCT||0.006);
const RR=Number(process.env.LIVE_TP_RR||2);
const CACHE={symbols:null,at:0};
function dec(v){const n=Number(v);return Number.isFinite(n)?n:0}
function floorStep(v,step){if(!step||step<=0)return v;const p=Math.max(0,Math.ceil(-Math.log10(step)));return Number((Math.floor((v+1e-12)/step)*step).toFixed(p))}
async function publicGet(path){const r=await fetch(BASE+path,{headers:{accept:'application/json'},cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.msg||'Binance public request failed');return j}
async function exchangeSymbol(symbol){if(!CACHE.symbols||Date.now()-CACHE.at>60000){const e=await publicGet('/fapi/v1/exchangeInfo');CACHE.symbols=new Map((e.symbols||[]).map(x=>[x.symbol,x]));CACHE.at=Date.now()}const s=CACHE.symbols.get(symbol);if(!s)throw Error('Symbol is not an active Binance Futures symbol');if(s.status!=='TRADING'||s.contractType!=='PERPETUAL'||s.quoteAsset!=='USDT')throw Error('Only trading USDT-M perpetuals are allowed');return s}
async function mark(symbol){const r=await fetch(BASE+'/fapi/v1/premiumIndex?symbol='+encodeURIComponent(symbol),{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.msg||'Unable to read Binance mark price');return dec(j.markPrice)}
async function signed(method,path,params){const key=process.env.BINANCE_API_KEY,secret=process.env.BINANCE_API_SECRET;if(!key||!secret)throw Error('Binance server credentials are not configured');const q=new URLSearchParams();for(const [k,v] of Object.entries(params||{})){if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v))}q.set('timestamp',String(Date.now()));q.set('recvWindow','5000');const sig=crypto.createHmac('sha256',secret).update(q.toString()).digest('hex');q.set('signature',sig);const r=await fetch(BASE+path+'?'+q.toString(),{method,headers:{'X-MBX-APIKEY':key,accept:'application/json'},cache:'no-store'});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}};if(!r.ok){const e=Error(data?.msg||data?.error||'Binance request failed');e.status=r.status;e.data=data;throw e}return data}
function quantityFor(symbol,requested,price,info){const lot=(info.filters||[]).find(x=>x.filterType==='LOT_SIZE')||{};const minQty=dec(lot.minQty),maxQty=dec(lot.maxQty),step=dec(lot.stepSize);let q=floorStep(dec(requested),step);if(q<minQty)throw Error('Calculated quantity is below Binance minimum quantity');if(maxQty&&q>maxQty)q=maxQty;const notional=q*price;if(notional>MAX_NOTIONAL)q=floorStep(MAX_NOTIONAL/price,step);if(q<minQty)throw Error('Live safety cap is below Binance minimum order size');return q}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});if(process.env.LIVE_UNLOCKED!=='true')return res.status(403).json({error:'LIVE execution is locked. Set LIVE_UNLOCKED=true only after paper testing.'});try{const b=req.body||{},action=String(b.action||'order');if(action==='order'){const symbol=String(b.symbol||'').trim().toUpperCase(),side=String(b.side||''),type=String(b.type||'MARKET');if(!/^[A-Z0-9_]{5,30}$/.test(symbol))return res.status(400).json({error:'Invalid symbol'});if(!['BUY','SELL'].includes(side))return res.status(400).json({error:'Invalid side'});if(type!=='MARKET')return res.status(400).json({error:'Only MARKET entry is enabled in the scanner'});const info=await exchangeSymbol(symbol),px=await mark(symbol),q=quantityFor(symbol,b.quantity,px,info);const p={symbol,side,type,quantity:String(q),newOrderRespType:'RESULT',selfTradePreventionMode:'EXPIRE_TAKER'};const entry=await signed('POST','/fapi/v1/order',p);const fill=dec(entry.avgPrice)||px;let protection=null;const stop=Math.min(Math.max(dec(b.stopPct)||DEFAULT_STOP,0.003),0.012),tp=side==='BUY'?fill*(1+stop*RR):fill*(1-stop*RR),sl=side==='BUY'?fill*(1-stop):fill*(1+stop),exitSide=side==='BUY'?'SELL':'BUY';if(process.env.LIVE_PROTECT_ORDERS!=='false'){try{const stopOrder=await signed('POST','/fapi/v1/algoOrder',{algoType:'CONDITIONAL',symbol,side:exitSide,type:'STOP_MARKET',quantity:String(q),triggerPrice:String(sl),closePosition:'false',reduceOnly:'true',workingType:'MARK_PRICE'});const takeOrder=await signed('POST','/fapi/v1/algoOrder',{algoType:'CONDITIONAL',symbol,side:exitSide,type:'TAKE_PROFIT_MARKET',quantity:String(q),triggerPrice:String(tp),closePosition:'false',reduceOnly:'true',workingType:'MARK_PRICE'});protection={stopOrderId:stopOrder.algoId||stopOrder.orderId,takeProfitOrderId:takeOrder.algoId||takeOrder.orderId,stopPrice:sl,takeProfitPrice:tp}}catch(e){try{await signed('POST','/fapi/v1/order',{symbol,side:exitSide,type:'MARKET',quantity:String(q),reduceOnly:'true',newOrderRespType:'RESULT'})}catch{}throw Error('Entry protection failed; scanner attempted emergency close: '+e.message)}}return res.status(200).json({entry,protection,serverPrice:px,quantity:q,notional:q*fill})}
if(action==='close'){const symbol=String(b.symbol||'').toUpperCase(),side=String(b.side||''),quantity=dec(b.quantity);if(!symbol||!['BUY','SELL'].includes(side)||quantity<=0)return res.status(400).json({error:'Invalid close request'});const info=await exchangeSymbol(symbol),px=await mark(symbol),q=quantityFor(symbol,quantity,px,info);const out=await signed('POST','/fapi/v1/order',{symbol,side,type:'MARKET',quantity:String(q),reduceOnly:'true',newOrderRespType:'RESULT'});return res.status(200).json(out)}
if(action==='cancelAll'){const symbol=String(b.symbol||'').toUpperCase();if(!symbol)return res.status(400).json({error:'Symbol required'});return res.status(200).json(await signed('DELETE','/fapi/v1/allOpenOrders',{symbol}))}
return res.status(400).json({error:'Unsupported trading action'})}catch(e){return res.status(e.status||502).json({error:e.message,binance:e.data||null})}}